#!/usr/bin/env python3
"""Check that vendored CellScript has absorbed the parent checkout.

The parent CellScript repository uses gitlinks for several subprojects, while
Myelin vendors those trees as ordinary directories under `cellscript/`.  This
checker compares the parent working tree, including dirty tracked files and
non-ignored untracked source files, against Myelin's flattened copy.

Some differences are intentional Myelin adaptations.  They are allowed only
when the exact parent/Myelin file pair still matches the recorded hash, so a
future parent-side change in the same file fails closed instead of hiding in a
path whitelist.
"""

from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from pathlib import Path


GITLINK_PATHS = {
    "editors/vscode-cellscript",
    "proposals/evolving-dob/evolving-dob-profile-v1",
    "proposals/novaseal",
    "tests/benchmarks",
    "website",
}

SKIP_TRACKED_PREFIXES = (
    ".cap/",
)

SKIP_UNTRACKED_PARTS = {
    ".cap",
    ".mavis",
    ".playwright-mcp",
    ".git",
    ".idea",
    ".vscode",
    ".wrangler",
    "__pycache__",
    "node_modules",
    "target",
}

SKIP_UNTRACKED_SUFFIXES = (
    ".DS_Store",
    ".pyc",
    ".pyo",
)

EXPECTED_ALLOWED_DIFFS = {
    ".gitignore": (
        "Myelin ignores local Playwright artefacts and keeps flattened proposal paths visible.",
        "640036cedcf651944103438f54489c93da449089f4c8228279000778b1b15e46",
    ),
    "crates/cellscript-ckb-adapter/Cargo.toml": (
        "Myelin's vendored depth needs a different ckb-sdk-rust sibling path.",
        "8562c31efd99a956734779e52109fde8590519e67ab1a05c8b3991abd471cc05",
    ),
    "scripts/cellscript_ckb_release_gate.sh": (
        "Myelin bootstraps VS Code extension dependencies before release-gate validation.",
        "8abde4a5cd7d7af5a1eebfa1860c8789e5a7084d2af85976a8ff194bbc96955b",
    ),
    "scripts/cellscript_gate.sh": (
        "Myelin resolves the sibling CKB checkout and shared Cargo target for local gates.",
        "903bc130db07289515320f33198d4f8c0d0a1c772089a4a5f0803a7a2e9a32cd",
    ),
    "tools/ckb-tx-measure/Cargo.toml": (
        "Myelin's vendored depth needs a different sibling CKB path.",
        "e07c695f81ede25f4213b65930a85d3e081aa6cb67c1797e6cafb0a132ec5554",
    ),
    "roadmap/CELLSCRIPT_0_13_ROADMAP.md": (
        "Myelin normalises parent trailing whitespace so git diff --check remains clean.",
        "f64dc198329daab6dadf19a71b3b830404050f83f37ca85f83d37d8e66d897c3",
    ),
    "proposals/evolving-dob/evolving-dob-profile-v1/.gitignore": (
        "Myelin normalises parent trailing blank lines so git diff --check remains clean.",
        "542b77ba483660db2e6769b38a8b40fb2f3cbe11cd13e7c797a94bbbb7938765",
    ),
    "proposals/novaseal/agreement-profile-v0/Cell.toml": (
        "NovaSeal verifier pins were regenerated by Myelin's passing release gate.",
        "fb6238e8dd65c0f0cb1d2953c32aec8e58a1c048d7cd49df5683ca3807a54574",
    ),
    "proposals/novaseal/btc-transaction-commitment-profile-v0/Cell.toml": (
        "NovaSeal verifier pins were regenerated by Myelin's passing release gate.",
        "c37312632db70e9c42715579c35a556c49c2e1f686b331c046530ef0a851b814",
    ),
    "proposals/novaseal/btc-utxo-seal-profile-v0/Cell.toml": (
        "NovaSeal verifier pins were regenerated by Myelin's passing release gate.",
        "7544bc529f95d6df18d5d8f11a3e42b31c93c7cc9f57fc43a553581cd6f1a2ff",
    ),
    "proposals/novaseal/dual-seal-profile-v0/Cell.toml": (
        "NovaSeal verifier pins were regenerated by Myelin's passing release gate.",
        "fd7cac95b806a31f914178b4733f5fb8c272e552251e64e675458643a2abbedc",
    ),
    "proposals/novaseal/fiber-candidate-profile-v0/Cell.toml": (
        "NovaSeal verifier pins were regenerated by Myelin's passing release gate.",
        "e12dd7b733148a290bcb7a8779795fb15501975aeee30883875a9e3f1704f583",
    ),
    "proposals/novaseal/fungible-xudt-profile-v0/Cell.toml": (
        "NovaSeal verifier pins were regenerated by Myelin's passing release gate.",
        "f81d7c68fcfeebf67aaf61f7176c9749074afc35f751974d78710fccf2060c9b",
    ),
    "proposals/novaseal/rwa-receipt-profile-v0/Cell.toml": (
        "NovaSeal verifier pins were regenerated by Myelin's passing release gate.",
        "69c08b9238f7498efa1973ce697ed628c891179416f5fc5df7bd19785237d1f5",
    ),
    "proposals/novaseal/rwa-receipt-profile-v0/proofs/legal_registry_review_evidence.template.json": (
        "NovaSeal RWA profile source hash was regenerated by Myelin's passing release gate.",
        "799a059ebe705fde2342701ff4e2e4dff9c18e49551100961b896181a60a6782",
    ),
    "proposals/novaseal/v0-mvp-skeleton/Cell.toml": (
        "NovaSeal verifier pins were regenerated by Myelin's passing release gate.",
        "b7952faee0b620e5f3e5609fc78ebb23e2d2a2e36faa88e3f235c29f02779c61",
    ),
    "proposals/novaseal/v0-mvp-skeleton/docs/CKB_VM_CHILD_VERIFIER.md": (
        "NovaSeal verifier pins were regenerated by Myelin's passing release gate.",
        "54033635db8f5d7f1ac24943716b41df5a2d6048ad6828aac1887056c6e41ae4",
    ),
    "proposals/novaseal/v0-mvp-skeleton/docs/RISCV_SHELL_ARTIFACT.md": (
        "NovaSeal verifier pins were regenerated by Myelin's passing release gate.",
        "7a0574ba9ea08adf25bd09c7952fe7c560598c5a351282d6155237e5a1bf4761",
    ),
    "proposals/novaseal/v0-mvp-skeleton/docs/RISCV_VERIFIER_SHELL.md": (
        "NovaSeal verifier pins were regenerated by Myelin's passing release gate.",
        "f71d1ee7aded6cfe20b47eeeacede7dbb9e9835b567ad882ab248af460c62bdb",
    ),
    "proposals/novaseal/v0-mvp-skeleton/proofs/bip340_external_tcb_review_attestation.template.json": (
        "NovaSeal verifier pins were regenerated by Myelin's passing release gate.",
        "a8a7ff2a6c9904081b6ecb0fb8f3b68565a93a2f7672d00e6eb6b4acf40f9d87",
    ),
    "proposals/novaseal/v0-mvp-skeleton/proofs/proofplan_mapping.json": (
        "NovaSeal verifier pins were regenerated by Myelin's passing release gate.",
        "7174c7f74725b2d61f32da5f0ef1ac3ca5556e1d26b61c346535dd59c05837ba",
    ),
    "proposals/novaseal/v0-mvp-skeleton/proofs/public_shared_cell_dep_attestation.template.json": (
        "NovaSeal verifier pins were regenerated by Myelin's passing release gate.",
        "b8fd61892b01d6f914c39496047baf00c6ed9e794c6717fbc4795b25c2df4641",
    ),
    "proposals/novaseal/.gitignore": (
        "Myelin normalises parent trailing blank lines so git diff --check remains clean.",
        "542b77ba483660db2e6769b38a8b40fb2f3cbe11cd13e7c797a94bbbb7938765",
    ),
    "tests/benchmarks/.gitignore": (
        "Myelin normalises parent trailing blank lines so git diff --check remains clean.",
        "542b77ba483660db2e6769b38a8b40fb2f3cbe11cd13e7c797a94bbbb7938765",
    ),
    "website/src/data/registry-packages.json": (
        "Myelin regenerates registry package source_revision from the vendored commit.",
        "31f3b043cc7c4d1ab0a5d8313e0e0c64d5a27b54cc90a4c0be26171290dbae62",
    ),
    "website/src/i18n/translations.ts": (
        "Myelin keeps homepage Registry copy required by the release tooling validator.",
        "5ef611ef9eb3a8c0bc7ab5d509fd4ba2bd4f85dbcd69ed453338b10c36ae478d",
    ),
    "website/src/pages/index.astro": (
        "Myelin keeps the homepage CellScript Registry boundary required by release validation.",
        "3bc3f5fb7e6a46e842b59b2824291e2388c486607dbb7f413d5b3b02eb14b37e",
    ),
    "website/src/styles/global.css": (
        "Myelin styles the homepage Registry boundary required by release validation.",
        "f856ab18ca2d6a6c83a8d2ecb24579a22810fa4d6043e72eb8ad29474b074d3e",
    ),
}


def run_git(repo: Path, args: list[str]) -> list[str]:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    return [line for line in result.stdout.splitlines() if line]


def is_skipped_tracked(path: str) -> bool:
    return path.startswith(SKIP_TRACKED_PREFIXES)


def is_skipped_untracked(path: str) -> bool:
    parts = set(Path(path).parts)
    if parts & SKIP_UNTRACKED_PARTS:
        return True
    return path.endswith(SKIP_UNTRACKED_SUFFIXES)


def repo_files(repo: Path, *, skip_gitlinks: bool) -> set[str]:
    files: set[str] = set()
    for path in run_git(repo, ["ls-files"]):
        if skip_gitlinks and path in GITLINK_PATHS:
            continue
        if is_skipped_tracked(path):
            continue
        files.add(path)
    for path in run_git(repo, ["ls-files", "--others", "--exclude-standard"]):
        if skip_gitlinks and path in GITLINK_PATHS:
            continue
        if is_skipped_untracked(path):
            continue
        files.add(path)
    return files


def pair_hash(parent_path: Path, vendored_path: Path) -> str:
    digest = hashlib.sha256()
    digest.update(parent_path.read_bytes())
    digest.update(b"\0MYELIN\0")
    digest.update(vendored_path.read_bytes())
    return digest.hexdigest()


def compare_file(label: str, parent_path: Path, vendored_path: Path) -> tuple[str, str | None]:
    parent_exists = parent_path.exists()
    vendored_exists = vendored_path.exists()
    if not parent_exists and not vendored_exists:
        return "match", None
    if parent_exists != vendored_exists:
        return "unexpected", "missing in vendored copy" if parent_exists else "deleted upstream but present in vendored copy"
    if parent_path.read_bytes() == vendored_path.read_bytes():
        return "match", None

    allowed = EXPECTED_ALLOWED_DIFFS.get(label)
    if allowed is None:
        return "unexpected", "content differs"

    reason, expected_hash = allowed
    actual_hash = pair_hash(parent_path, vendored_path)
    if actual_hash != expected_hash:
        return "stale-allowed", f"{reason}; expected pair hash {expected_hash}, got {actual_hash}"
    return "allowed", reason


def compare_tree(label_prefix: str, parent_tree: Path, vendored_tree: Path, *, skip_gitlinks: bool = False) -> dict[str, list[str]]:
    results = {"unexpected": [], "stale-allowed": [], "allowed": [], "match": []}
    for rel in sorted(repo_files(parent_tree, skip_gitlinks=skip_gitlinks)):
        label = f"{label_prefix}/{rel}" if label_prefix else rel
        status, detail = compare_file(label, parent_tree / rel, vendored_tree / rel)
        if status == "match":
            results["match"].append(label)
        elif status == "allowed":
            results["allowed"].append(f"{label}: {detail}")
        else:
            results[status].append(f"{label}: {detail}")
    return results


def merge_results(target: dict[str, list[str]], source: dict[str, list[str]]) -> None:
    for key, values in source.items():
        target[key].extend(values)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--parent",
        type=Path,
        default=Path(__file__).resolve().parents[1].parent / "CellScript",
        help="parent CellScript checkout to compare against (default: ../CellScript)",
    )
    parser.add_argument(
        "--vendored",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "cellscript",
        help="vendored CellScript directory (default: ./cellscript)",
    )
    args = parser.parse_args()

    parent = args.parent.resolve()
    vendored = args.vendored.resolve()
    if not parent.is_dir():
        print(f"parent CellScript checkout not found: {parent}", file=sys.stderr)
        return 2
    if not vendored.is_dir():
        print(f"vendored CellScript directory not found: {vendored}", file=sys.stderr)
        return 2

    results = {"unexpected": [], "stale-allowed": [], "allowed": [], "match": []}
    merge_results(results, compare_tree("", parent, vendored, skip_gitlinks=True))
    for gitlink in sorted(GITLINK_PATHS):
        merge_results(results, compare_tree(gitlink, parent / gitlink, vendored / gitlink))

    failures = results["unexpected"] + results["stale-allowed"]
    if failures:
        print("CellScript parent parity check failed.")
        if results["unexpected"]:
            print("\nUnexpected upstream differences:")
            for item in results["unexpected"]:
                print(f"  - {item}")
        if results["stale-allowed"]:
            print("\nAllowed paths changed and need review:")
            for item in results["stale-allowed"]:
                print(f"  - {item}")
        print(
            f"\nCompared {len(results['match']) + len(results['allowed']) + len(failures)} files; "
            f"{len(results['allowed'])} intentional Myelin differences matched their recorded hashes."
        )
        return 1

    print("CellScript parent parity check passed.")
    print(
        f"Compared {len(results['match']) + len(results['allowed'])} files; "
        f"{len(results['allowed'])} intentional Myelin differences matched their recorded hashes."
    )
    if results["allowed"]:
        print("\nIntentional Myelin differences:")
        for item in results["allowed"]:
            print(f"  - {item}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
