// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Myelin developers
//
// Myelin protocol CLI.

use clap::{Args, Parser, Subcommand};
use myelin_consensus::{
    CommitteeCertificate, CommitteeSignature, CommitteeValidator, ConsensusConfig, ConsensusEngine, ConsensusKind, MyelinBlock,
    SelectedConsensus, StaticClosedCommittee, StaticCommitteeConfig, Tendermint, TendermintConfig,
};
use myelin_exec::{
    build_cell_tx_execution_report, deserialize_transaction_molecule, project_cell_tx_to_ckb, serialize_transaction_molecule,
    CellInput, CellOutput, CellTx, CkbProjectionReport, OutPoint, ResolvedCell, Script, ScriptVersion, SemanticProfile,
    SimpleDataProvider, TransactionScriptVerifier, VmSemantics,
};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::{fs, path::PathBuf, process::Command, sync::Arc, time::Instant};

#[derive(Debug, Parser)]
#[command(name = "myelin")]
#[command(about = "Myelin finite Cell ledger tools")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Debug, Subcommand)]
enum Commands {
    /// CellTx report commands.
    Celltx(CelltxArgs),
    /// Committee finality commands.
    Committee(CommitteeArgs),
    /// Teeworlds fixture commands.
    Teeworlds(TeeworldsArgs),
}

#[derive(Debug, Args)]
struct CelltxArgs {
    #[command(subcommand)]
    command: CelltxCommand,
}

#[derive(Debug, Subcommand)]
enum CelltxCommand {
    /// Emit a deterministic report for a built-in simple CellTx.
    SimpleReport(OutputArgs),
}

#[derive(Debug, Args)]
struct CommitteeArgs {
    #[command(subcommand)]
    command: CommitteeCommand,
}

#[derive(Debug, Subcommand)]
enum CommitteeCommand {
    /// Finalise a deterministic demo block with a configured static committee.
    FinaliseDemo(CommitteeFinaliseDemoArgs),
}

#[derive(Debug, Args)]
struct CommitteeFinaliseDemoArgs {
    /// TOML consensus config.
    #[arg(long)]
    config: PathBuf,
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct TeeworldsArgs {
    #[command(subcommand)]
    command: TeeworldsCommand,
}

#[derive(Debug, Subcommand)]
enum TeeworldsCommand {
    /// Inspect a CKB mock transaction generated by xxuejie's teeworlds-cli.
    Inspect(TeeworldsInspectArgs),
    /// Measure Teeworlds fixture ingestion and chunk commitment generation.
    Bench(TeeworldsBenchArgs),
    /// Run xxuejie's fixture builder, then benchmark the generated mock transaction.
    BuildFixture(TeeworldsBuildFixtureArgs),
    /// Probe the Teeworlds replayer through Myelin's CKB-VM verifier path.
    VmProbe(TeeworldsVmProbeArgs),
    /// Emit a single-chunk court input bundle for a disputed Teeworlds chunk.
    CourtBundle(TeeworldsCourtBundleArgs),
    /// Verify a previously emitted single-chunk court input bundle.
    VerifyCourtBundle(TeeworldsVerifyCourtBundleArgs),
    /// Check local prerequisites for running xxuejie's Teeworlds CKB fixture.
    Doctor(TeeworldsDoctorArgs),
}

#[derive(Debug, Args)]
struct TeeworldsInspectArgs {
    /// CKB mock transaction JSON from `teeworlds-cli utils build-test-tx`.
    #[arg(long)]
    mock_tx: PathBuf,
    /// Tape chunk size in bytes.
    #[arg(long, default_value_t = 262_144)]
    chunk_bytes: usize,
    /// Consensus engine for the finality evidence: "static-closed-committee"
    /// (default) or "tendermint".
    #[arg(long, default_value = "static-closed-committee")]
    consensus: String,
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct TeeworldsBenchArgs {
    /// CKB mock transaction JSON from `teeworlds-cli utils build-test-tx`.
    #[arg(long)]
    mock_tx: PathBuf,
    /// Tape chunk size in bytes.
    #[arg(long, default_value_t = 262_144)]
    chunk_bytes: usize,
    /// Number of measured runs.
    #[arg(long, default_value_t = 3)]
    runs: usize,
    /// Consensus engine for the finality evidence: "static-closed-committee"
    /// (default) or "tendermint".
    #[arg(long, default_value = "static-closed-committee")]
    consensus: String,
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct TeeworldsBuildFixtureArgs {
    /// Root of the cloned xxuejie Teeworlds repository.
    #[arg(long, default_value = "/Users/arthur/RustroverProjects/teeworlds")]
    teeworlds_root: PathBuf,
    /// Replayer binary passed to `teeworlds-cli utils build-test-tx`.
    #[arg(long)]
    replayer: PathBuf,
    /// Input tape passed to `teeworlds-cli utils build-test-tx`.
    #[arg(long)]
    tape: PathBuf,
    /// Stripped map passed to `teeworlds-cli utils build-test-tx`.
    #[arg(long)]
    map: PathBuf,
    /// Game config passed to `teeworlds-cli utils build-test-tx`.
    #[arg(long)]
    config: PathBuf,
    /// Output CKB mock transaction JSON path.
    #[arg(long)]
    mock_tx_output: PathBuf,
    /// Tape chunk size in bytes for the Myelin benchmark.
    #[arg(long, default_value_t = 262_144)]
    chunk_bytes: usize,
    /// Number of measured Myelin benchmark runs.
    #[arg(long, default_value_t = 3)]
    runs: usize,
    /// Consensus engine for the finality evidence: "static-closed-committee"
    /// (default) or "tendermint".
    #[arg(long, default_value = "static-closed-committee")]
    consensus: String,
    /// Optional output JSON path for the combined report.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct TeeworldsVmProbeArgs {
    /// Replayer binary to execute as the type script.
    #[arg(long)]
    replayer: PathBuf,
    /// Input tape witness.
    #[arg(long)]
    tape: PathBuf,
    /// Stripped map witness.
    #[arg(long)]
    map: PathBuf,
    /// Game config witness.
    #[arg(long)]
    config: PathBuf,
    /// Maximum VM cycles.
    #[arg(long, default_value_t = 70_000_000)]
    max_cycles: u64,
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct TeeworldsCourtBundleArgs {
    /// CKB mock transaction JSON from `teeworlds-cli utils build-test-tx`.
    #[arg(long)]
    mock_tx: PathBuf,
    /// Tape chunk size in bytes.
    #[arg(long, default_value_t = 262_144)]
    chunk_bytes: usize,
    /// Zero-based disputed chunk index.
    #[arg(long, default_value_t = 0)]
    chunk_index: usize,
    /// Consensus engine for the bundle evidence: "static-closed-committee"
    /// (default) or "tendermint".
    #[arg(long, default_value = "static-closed-committee")]
    consensus: String,
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct TeeworldsVerifyCourtBundleArgs {
    /// JSON bundle emitted by `teeworlds court-bundle`.
    #[arg(long)]
    bundle: PathBuf,
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct TeeworldsDoctorArgs {
    /// Root of the cloned xxuejie Teeworlds repository.
    #[arg(long, default_value = "/Users/arthur/RustroverProjects/teeworlds")]
    teeworlds_root: PathBuf,
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct OutputArgs {
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, thiserror::Error)]
enum CliError {
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("json error: {0}")]
    Json(#[from] serde_json::Error),
    #[error("consensus error: {0}")]
    Consensus(#[from] myelin_consensus::ConsensusError),
    #[error("invalid fixture: {0}")]
    InvalidFixture(String),
}

type Result<T> = std::result::Result<T, CliError>;

fn main() {
    if let Err(error) = run() {
        eprintln!("error: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Commands::Celltx(args) => match args.command {
            CelltxCommand::SimpleReport(args) => write_json(args.out, &simple_celltx_report()?),
        },
        Commands::Committee(args) => match args.command {
            CommitteeCommand::FinaliseDemo(args) => {
                let report = finalise_demo_from_config(args.config)?;
                write_json(args.out, &report)
            }
        },
        Commands::Teeworlds(args) => match args.command {
            TeeworldsCommand::Inspect(args) => {
                let report = inspect_teeworlds_mock_tx(args.mock_tx, args.chunk_bytes, &args.consensus)?;
                write_json(args.out, &report)
            }
            TeeworldsCommand::Bench(args) => {
                let report = bench_teeworlds_mock_tx(args.mock_tx, args.chunk_bytes, args.runs, &args.consensus)?;
                write_json(args.out, &report)
            }
            TeeworldsCommand::BuildFixture(args) => {
                let out = args.out.clone();
                let report = build_and_bench_teeworlds_fixture(args)?;
                write_json(out, &report)
            }
            TeeworldsCommand::VmProbe(args) => {
                let report = teeworlds_vm_probe(&args)?;
                write_json(args.out, &report)
            }
            TeeworldsCommand::CourtBundle(args) => {
                let report = teeworlds_court_bundle(args.mock_tx, args.chunk_bytes, args.chunk_index, &args.consensus)?;
                write_json(args.out, &report)
            }
            TeeworldsCommand::VerifyCourtBundle(args) => {
                let report = verify_teeworlds_court_bundle(args.bundle)?;
                write_json(args.out, &report)
            }
            TeeworldsCommand::Doctor(args) => {
                let report = teeworlds_doctor(&args.teeworlds_root);
                write_json(args.out, &report)
            }
        },
    }
}

fn write_json<T: Serialize>(path: Option<PathBuf>, value: &T) -> Result<()> {
    let json = serde_json::to_string_pretty(value)?;
    if let Some(path) = path {
        fs::write(path, json)?;
    } else {
        println!("{json}");
    }
    Ok(())
}

fn simple_celltx_report() -> Result<serde_json::Value> {
    let tx = CellTx::new(
        vec![CellInput::new(OutPoint::new([1; 32], 0), 0)],
        vec![],
        vec![CellOutput { lock: Script::new([2; 32], 1, vec![0x42]), type_: None, capacity: 100 }],
        vec![b"myelin-simple-output".to_vec()],
        vec![b"myelin-simple-witness".to_vec()],
    )
    .map_err(|error| CliError::InvalidFixture(error.to_owned()))?;
    let report = build_cell_tx_execution_report(&tx, [0; 32]);
    Ok(serde_json::to_value(report)?)
}

#[derive(Clone, Debug, Serialize)]
struct CommitteeDemoReport {
    consensus_kind: &'static str,
    block_hash: String,
    quorum_weight: u64,
    signer_ids: Vec<String>,
    certificate_height: u64,
    certificate_round: Option<u32>,
    certificate_step: &'static str,
    finalised: bool,
}

fn finalise_demo_from_config(path: PathBuf) -> Result<CommitteeDemoReport> {
    let config_text = fs::read_to_string(path)?;
    let config = ConsensusConfig::from_toml_str(&config_text)?;
    let selected = SelectedConsensus::from_config(config.clone())?;
    match config.kind {
        ConsensusKind::StaticClosedCommittee => finalise_static_demo(config, selected),
        ConsensusKind::Tendermint => finalise_tendermint_demo(config, selected),
    }
}

fn finalise_static_demo(config: ConsensusConfig, selected: SelectedConsensus) -> Result<CommitteeDemoReport> {
    let static_config = config
        .static_committee
        .ok_or_else(|| CliError::InvalidFixture("demo finality requires a static committee config".to_owned()))?;
    let committee = StaticClosedCommittee::new(static_config.clone())?;
    let block = demo_block(vec![[0xA1; 32]], ConsensusKind::StaticClosedCommittee);
    let block_hash = block.hash();
    let height = block.number;
    let signer_ids = quorum_signers(&static_config)?;
    let signer_refs = signer_ids.iter().map(String::as_str).collect::<Vec<_>>();
    let certificate = committee.certificate_for_fixture(block_hash, &signer_refs)?;
    selected.finalise_block(block, certificate)?;
    Ok(CommitteeDemoReport {
        consensus_kind: ConsensusKind::StaticClosedCommittee.as_str(),
        block_hash: hex::encode(block_hash),
        quorum_weight: static_config.quorum_weight,
        signer_ids,
        certificate_height: height,
        certificate_round: None,
        certificate_step: "commit",
        finalised: true,
    })
}

fn finalise_tendermint_demo(config: ConsensusConfig, selected: SelectedConsensus) -> Result<CommitteeDemoReport> {
    let tendermint_config =
        config.tendermint.ok_or_else(|| CliError::InvalidFixture("demo finality requires a tendermint config".to_owned()))?;
    let tendermint = Tendermint::new(tendermint_config.clone())?;
    let block = demo_block(vec![[0xB1; 32]], ConsensusKind::Tendermint);
    let block_hash = block.hash();
    let height = block.number;
    let round = 0;
    let signer_ids = tendermint_quorum_signers(&tendermint_config)?;
    let signer_refs = signer_ids.iter().map(String::as_str).collect::<Vec<_>>();
    let certificate = tendermint.precommit_certificate_for_fixture(block_hash, height, round, &signer_refs)?;
    match selected {
        SelectedConsensus::Tendermint(engine) => {
            engine.finalise_block_with_precommit(block, round, certificate)?;
        }
        other => {
            return Err(myelin_consensus::ConsensusError::WrongEngine {
                expected: ConsensusKind::Tendermint.as_str(),
                actual: other.kind().as_str(),
            }
            .into());
        }
    }
    Ok(CommitteeDemoReport {
        consensus_kind: ConsensusKind::Tendermint.as_str(),
        block_hash: hex::encode(block_hash),
        quorum_weight: tendermint_config.quorum_power,
        signer_ids,
        certificate_height: height,
        certificate_round: Some(round),
        certificate_step: "precommit",
        finalised: true,
    })
}

fn quorum_signers(config: &StaticCommitteeConfig) -> Result<Vec<String>> {
    let mut signers = Vec::new();
    let mut weight = 0u64;
    for validator in &config.validators {
        signers.push(validator.id.clone());
        weight =
            weight.checked_add(validator.weight).ok_or_else(|| CliError::InvalidFixture("committee weight overflow".to_owned()))?;
        if weight >= config.quorum_weight {
            return Ok(signers);
        }
    }
    Err(CliError::InvalidFixture("static committee config cannot satisfy quorum".to_owned()))
}

fn tendermint_quorum_signers(config: &TendermintConfig) -> Result<Vec<String>> {
    let mut signers = Vec::new();
    let mut power = 0u64;
    for validator in &config.validators {
        signers.push(validator.id.clone());
        power = power.checked_add(validator.weight).ok_or_else(|| CliError::InvalidFixture("validator power overflow".to_owned()))?;
        if power >= config.quorum_power {
            return Ok(signers);
        }
    }
    Err(CliError::InvalidFixture("tendermint config cannot satisfy quorum".to_owned()))
}

#[derive(Clone, Debug, Serialize)]
struct TeeworldsFixtureReport {
    source: String,
    mock_tx_json_hash: String,
    witness_count: usize,
    witness_bytes: Vec<usize>,
    tape_bytes: usize,
    map_bytes: usize,
    config_bytes: usize,
    chunk_bytes: usize,
    ckb_projection_possible: bool,
    chunks: Vec<TeeworldsChunkReport>,
    finality: CommitteeDemoReport,
}

#[derive(Clone, Debug, Serialize)]
struct TeeworldsChunkReport {
    index: usize,
    offset: usize,
    byte_len: usize,
    commitment: String,
    ckb_projection: TeeworldsChunkProjectionReport,
}

#[derive(Clone, Debug, Serialize)]
struct TeeworldsChunkProjectionReport {
    semantic_profile: String,
    ckb_projection_possible: bool,
    blockers: Value,
    warnings: Value,
    source_txid: String,
    ckb_raw_tx_hash: Option<String>,
    ckb_wtx_hash: Option<String>,
    molecule_transaction_bytes: Option<usize>,
    input_count: usize,
    output_count: usize,
    witness_count: usize,
}

#[derive(Debug, Serialize)]
struct TeeworldsBenchmarkReport {
    fixture: TeeworldsFixtureReport,
    runs: Vec<TeeworldsBenchmarkRun>,
    average_elapsed_ns: u128,
}

#[derive(Debug, Serialize)]
struct TeeworldsBenchmarkRun {
    index: usize,
    elapsed_ns: u128,
    tape_bytes: usize,
    chunk_count: usize,
}

#[derive(Debug, Serialize)]
struct TeeworldsBuildFixtureReport {
    teeworlds_root: String,
    command: Vec<String>,
    builder_stdout: String,
    builder_stderr: String,
    mock_tx_output: String,
    benchmark: TeeworldsBenchmarkReport,
}

#[derive(Debug, Serialize)]
struct TeeworldsVmProbeReport {
    replayer: String,
    tape_bytes: usize,
    map_bytes: usize,
    config_bytes: usize,
    max_cycles: u64,
    ckb_strict: bool,
    success: bool,
    cycles: Option<u64>,
    error: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
struct TeeworldsBundleBlock {
    /// Block format version.
    version: u32,
    /// Parent block hash (zero for the session genesis block).
    parent_hash: String,
    /// Session-local block number.
    number: u64,
    /// Block timestamp in milliseconds.
    timestamp_ms: u64,
    /// Consensus engine kind: "static-closed-committee" or "tendermint".
    consensus_kind: String,
    /// State root before the block's transitions.
    state_root_before: String,
    /// State root after the block's transitions.
    state_root_after: String,
    /// Ordered CellTx commitments admitted into this block.
    ordered_cell_tx_commitments: Vec<String>,
    /// Published data-availability chunk commitments.
    data_commitments: Vec<String>,
    /// Commitment to the CellDAG scheduler report.
    scheduler_commitment: String,
    /// Block hash; MUST match `block.hash()` over the fields above.
    block_hash: String,
}

impl TeeworldsBundleBlock {
    fn to_myelin_block(&self) -> std::result::Result<MyelinBlock, String> {
        let parse_32 = |hex_str: &str, label: &str| -> std::result::Result<[u8; 32], String> {
            parse_hex_32(hex_str).ok_or_else(|| format!("{label} must be 32-byte hex"))
        };
        let consensus_kind = match self.consensus_kind.as_str() {
            "static-closed-committee" => ConsensusKind::StaticClosedCommittee,
            "tendermint" => ConsensusKind::Tendermint,
            other => return Err(format!("unknown consensus_kind in bundle block: {other}")),
        };
        let ordered_cell_tx_commitments = self
            .ordered_cell_tx_commitments
            .iter()
            .map(|h| parse_32(h, "ordered_cell_tx_commitments"))
            .collect::<std::result::Result<Vec<_>, String>>()?;
        let data_commitments =
            self.data_commitments.iter().map(|h| parse_32(h, "data_commitments")).collect::<std::result::Result<Vec<_>, String>>()?;
        Ok(MyelinBlock {
            version: self.version,
            parent_hash: parse_32(&self.parent_hash, "parent_hash")?,
            number: self.number,
            timestamp_ms: self.timestamp_ms,
            consensus_kind,
            state_root_before: parse_32(&self.state_root_before, "state_root_before")?,
            state_root_after: parse_32(&self.state_root_after, "state_root_after")?,
            ordered_cell_tx_commitments,
            data_commitments,
            scheduler_commitment: parse_32(&self.scheduler_commitment, "scheduler_commitment")?,
        })
    }
}

#[derive(Debug, Serialize, Clone)]
struct TeeworldsCourtBundleReport {
    source: String,
    mock_tx_json_hash: String,
    chunk_index: usize,
    chunk_offset: usize,
    chunk_bytes: usize,
    chunk_payload_hex: String,
    session_id: String,
    old_state_root: String,
    new_state_root: String,
    chunk_payload_hash: String,
    map_hash: String,
    config_hash: String,
    chunk_commitment: String,
    scheduler_report_hash: String,
    /// Canonical MyelinBlock whose data fields match the bundle's runtime
    /// evidence. The block's `block_hash()` MUST equal the hash that the
    /// static-closed-committee certificate or Tendermint precommit
    /// certificate is bound to. This is the data-binding guarantee the
    /// verifier relies on.
    block: TeeworldsBundleBlock,
    molecule_transaction_bytes: usize,
    molecule_transaction_hex: String,
    molecule_transaction_hash: String,
    challenge_payload_hash: String,
    ckb_projection: TeeworldsChunkProjectionReport,
    /// Selectable finality evidence: static closed committee OR Tendermint
    /// weighted precommit certificate. The same `signatures` field carries
    /// both modes; the `consensus_kind` field disambiguates.
    static_committee_evidence: StaticCommitteeEvidenceReport,
    /// Tendermint-only fields: precommit round, certificate step, height.
    /// `None` for static-closed-committee bundles.
    tendermint_evidence: Option<TendermintEvidenceReport>,
    court_verifiable: bool,
    l1_court_implemented: bool,
    notes: Vec<String>,
}

#[derive(Debug, Serialize)]
struct TeeworldsCourtBundleVerificationReport {
    bundle: String,
    valid: bool,
    checks: Vec<CourtBundleCheck>,
}

#[derive(Debug, Serialize)]
struct CourtBundleCheck {
    name: &'static str,
    ok: bool,
    expected: Option<String>,
    actual: Option<String>,
    detail: String,
}

#[derive(Debug, Deserialize)]
struct TeeworldsCourtBundleInput {
    chunk_payload_hex: String,
    chunk_payload_hash: String,
    chunk_commitment: String,
    molecule_transaction_hex: String,
    molecule_transaction_hash: String,
    challenge_payload_hash: String,
    old_state_root: String,
    new_state_root: String,
    scheduler_report_hash: String,
    ckb_projection: TeeworldsChunkProjectionInput,
    /// Canonical MyelinBlock whose data fields match the runtime evidence.
    /// The verifier recomputes `block.hash()` from these fields and asserts
    /// the result equals the active block hash that the finality certificate
    /// is bound to. This is the data-binding guarantee.
    block: TeeworldsBundleBlock,
    static_committee_evidence: StaticCommitteeEvidenceInput,
    /// Optional Tendermint precommit evidence. When present, the challenge
    /// payload hash binds to the Tendermint block hash and the static
    /// committee evidence block hash is reported for completeness only.
    tendermint_evidence: Option<TendermintEvidenceInput>,
}

#[derive(Debug, Deserialize)]
struct TeeworldsChunkProjectionInput {
    semantic_profile: String,
    ckb_projection_possible: bool,
    source_txid: String,
    ckb_raw_tx_hash: Option<String>,
    ckb_wtx_hash: Option<String>,
    molecule_transaction_bytes: Option<usize>,
}

#[derive(Debug, Deserialize)]
struct StaticCommitteeEvidenceInput {
    block_hash: String,
    quorum_weight: u64,
    signer_ids: Vec<String>,
    signatures: Vec<CommitteeSignatureEvidenceInput>,
    finalised: bool,
}

#[derive(Debug, Deserialize)]
struct TendermintEvidenceInput {
    block_hash: String,
    quorum_power: u64,
    height: u64,
    round: u32,
    signer_ids: Vec<String>,
    signatures: Vec<CommitteeSignatureEvidenceInput>,
    finalised: bool,
}

#[derive(Debug, Deserialize)]
struct CommitteeSignatureEvidenceInput {
    validator_id: String,
    signature: String,
    signature_hash: String,
}

#[derive(Clone, Debug, Serialize)]
struct StaticCommitteeEvidenceReport {
    consensus_kind: &'static str,
    block_hash: String,
    quorum_weight: u64,
    signer_ids: Vec<String>,
    signatures: Vec<CommitteeSignatureEvidenceReport>,
    finalised: bool,
}

#[derive(Clone, Debug, Serialize)]
struct TendermintEvidenceReport {
    consensus_kind: &'static str,
    block_hash: String,
    quorum_power: u64,
    height: u64,
    round: u32,
    signer_ids: Vec<String>,
    signatures: Vec<CommitteeSignatureEvidenceReport>,
    certificate_step: &'static str,
    finalised: bool,
}

#[derive(Clone, Debug, Serialize)]
struct CommitteeSignatureEvidenceReport {
    validator_id: String,
    signature: String,
    signature_hash: String,
}

#[derive(Debug, Serialize)]
struct TeeworldsDoctorReport {
    teeworlds_root: String,
    ready_for_rust_fixture_builder: bool,
    ready_for_ckb_replayer_build: bool,
    ready_for_myelin_vm_probe: bool,
    paths: Vec<PathCheck>,
    tools: Vec<ToolCheck>,
    notes: Vec<String>,
    next_commands: Vec<String>,
}

#[derive(Debug, Serialize)]
struct PathCheck {
    name: &'static str,
    path: String,
    exists: bool,
}

#[derive(Debug, Serialize)]
struct ToolCheck {
    name: &'static str,
    found: bool,
    path: Option<String>,
}

fn inspect_teeworlds_mock_tx(path: PathBuf, chunk_bytes: usize, consensus: &str) -> Result<TeeworldsFixtureReport> {
    if chunk_bytes == 0 {
        return Err(CliError::InvalidFixture("chunk-bytes must be non-zero".to_owned()));
    }
    let consensus_kind = parse_teeworlds_consensus(consensus)?;

    let bytes = fs::read(&path)?;
    let fixture_hash = *blake3::hash(&bytes).as_bytes();
    let mock_tx_json_hash = hex::encode(fixture_hash);
    let value = serde_json::from_slice::<Value>(&bytes)?;
    let witnesses = find_witnesses(&value)
        .ok_or_else(|| CliError::InvalidFixture("could not find a witnesses array in mock transaction JSON".to_owned()))?;
    if witnesses.len() < 4 {
        return Err(CliError::InvalidFixture(format!("expected at least 4 witnesses, got {}", witnesses.len())));
    }

    let witness_bytes = witnesses.iter().map(Vec::len).collect::<Vec<_>>();
    let tape = &witnesses[1];
    let map = &witnesses[2];
    let config = &witnesses[3];
    let map_hash = blake3_32(b"myelin:teeworlds-map:v1", map);
    let config_hash = blake3_32(b"myelin:teeworlds-config:v1", config);
    let chunks = tape
        .chunks(chunk_bytes)
        .enumerate()
        .map(|(index, chunk)| {
            let offset = index * chunk_bytes;
            let commitment = chunk_commitment(index, offset, chunk);
            let ckb_projection = teeworlds_chunk_projection(index, offset, chunk, commitment, map_hash, config_hash, fixture_hash);
            TeeworldsChunkReport { index, offset, byte_len: chunk.len(), commitment: hex::encode(commitment), ckb_projection }
        })
        .collect::<Vec<_>>();
    let ckb_projection_possible = chunks.iter().all(|chunk| chunk.ckb_projection.ckb_projection_possible);
    let finality = finalise_teeworlds_fixture_block(&chunks, consensus_kind);

    Ok(TeeworldsFixtureReport {
        source: path.display().to_string(),
        mock_tx_json_hash,
        witness_count: witnesses.len(),
        witness_bytes,
        tape_bytes: tape.len(),
        map_bytes: map.len(),
        config_bytes: config.len(),
        chunk_bytes,
        ckb_projection_possible,
        chunks,
        finality,
    })
}

fn parse_teeworlds_consensus(consensus: &str) -> Result<ConsensusKind> {
    match consensus {
        "static-closed-committee" | "static_closed_committee" => Ok(ConsensusKind::StaticClosedCommittee),
        "tendermint" => Ok(ConsensusKind::Tendermint),
        other => Err(CliError::InvalidFixture(format!("unknown consensus engine: {other}"))),
    }
}

fn teeworlds_doctor(teeworlds_root: &std::path::Path) -> TeeworldsDoctorReport {
    let rust_tools_manifest = teeworlds_root.join("rust-tools/Cargo.toml");
    let ckb_makefile = teeworlds_root.join("ckb/Makefile");
    let ckb_replayer = teeworlds_root.join("ckb/build/replayer_stripped");
    let generated_protocol = teeworlds_root.join("build/src/generated/protocol.cpp");
    let paths = vec![
        path_check("teeworlds-root", teeworlds_root.to_path_buf()),
        path_check("rust-tools-manifest", rust_tools_manifest.clone()),
        path_check("ckb-makefile", ckb_makefile),
        path_check("ckb-c-stdlib", teeworlds_root.join("ckb/ckb-c-stdlib")),
        path_check("ckb-musl", teeworlds_root.join("ckb/musl")),
        path_check("ckb-builtins", teeworlds_root.join("ckb/builtins")),
        path_check("ckb-libcxx", teeworlds_root.join("ckb/libcxx")),
        path_check("generated-protocol", generated_protocol),
        path_check("replayer-stripped", ckb_replayer.clone()),
    ];
    let tools = vec![
        tool_check("cargo"),
        tool_check("clang"),
        tool_check("clang++"),
        tool_check("ld.lld"),
        tool_check("llvm-objcopy"),
        tool_check("llvm-ar"),
        tool_check("cmake"),
        tool_check("make"),
        tool_check("python3"),
    ];

    let path_exists = |name: &str| paths.iter().find(|path| path.name == name).map(|path| path.exists).unwrap_or(false);
    let tool_found = |name: &str| tools.iter().find(|tool| tool.name == name).map(|tool| tool.found).unwrap_or(false);

    let ready_for_rust_fixture_builder = path_exists("teeworlds-root") && path_exists("rust-tools-manifest") && tool_found("cargo");
    let ready_for_ckb_replayer_build = path_exists("teeworlds-root")
        && path_exists("ckb-makefile")
        && path_exists("ckb-c-stdlib")
        && path_exists("ckb-musl")
        && path_exists("ckb-builtins")
        && path_exists("ckb-libcxx")
        && path_exists("generated-protocol")
        && tool_found("clang")
        && tool_found("clang++")
        && tool_found("ld.lld")
        && tool_found("llvm-objcopy")
        && tool_found("llvm-ar")
        && tool_found("make");
    let ready_for_myelin_vm_probe = path_exists("replayer-stripped");

    let mut notes = Vec::new();
    if !path_exists("generated-protocol") {
        notes.push("Run Teeworlds' top-level CMake build first so build/src/generated/protocol.cpp exists.".to_owned());
    }
    if !path_exists("replayer-stripped") {
        notes.push("Build teeworlds/ckb/build/replayer_stripped before probing the real Teeworlds VM path.".to_owned());
    }
    if !tool_found("llvm-objcopy") || !tool_found("llvm-ar") || !tool_found("ld.lld") {
        notes.push("Install LLVM tools and ensure llvm-objcopy, llvm-ar, and ld.lld are on PATH.".to_owned());
    }
    if !ready_for_ckb_replayer_build {
        notes.push("The CKB replayer build is not ready on this machine yet; Myelin can still run fixture-builder and VM-probe commands when supplied with a valid ELF.".to_owned());
    }

    TeeworldsDoctorReport {
        teeworlds_root: teeworlds_root.display().to_string(),
        ready_for_rust_fixture_builder,
        ready_for_ckb_replayer_build,
        ready_for_myelin_vm_probe,
        paths,
        tools,
        notes,
        next_commands: vec![
            "cd /Users/arthur/RustroverProjects/teeworlds && git submodule update --init --recursive".to_owned(),
            "cd /Users/arthur/RustroverProjects/teeworlds && cmake -S . -B build && cmake --build build --target teeworlds_replayer -j4".to_owned(),
            "cd /Users/arthur/RustroverProjects/teeworlds/ckb && PATH=\"/opt/homebrew/opt/llvm/bin:$PATH\" make CLANG=/opt/homebrew/opt/llvm/bin/clang LD=/opt/homebrew/bin/ld.lld".to_owned(),
            "cargo run -p myelin-cli -- teeworlds vm-probe --replayer /Users/arthur/RustroverProjects/teeworlds/ckb/build/replayer_stripped --tape path/to/tape.bin --map path/to/stripped.map --config path/to/test_game.cfg".to_owned(),
        ],
    }
}

fn path_check(name: &'static str, path: PathBuf) -> PathCheck {
    PathCheck { name, exists: path.exists(), path: path.display().to_string() }
}

fn tool_check(name: &'static str) -> ToolCheck {
    let path = find_executable(name);
    ToolCheck { name, found: path.is_some(), path: path.map(|path| path.display().to_string()) }
}

fn find_executable(name: &str) -> Option<PathBuf> {
    let candidate = std::path::Path::new(name);
    if candidate.components().count() > 1 && is_executable(candidate) {
        return Some(candidate.to_path_buf());
    }
    let path_match = std::env::var_os("PATH")
        .and_then(|path_var| std::env::split_paths(&path_var).map(|dir| dir.join(name)).find(|candidate| is_executable(candidate)));
    path_match.or_else(|| fallback_tool_dirs().into_iter().map(|dir| dir.join(name)).find(|candidate| is_executable(candidate)))
}

fn fallback_tool_dirs() -> Vec<PathBuf> {
    ["/opt/homebrew/opt/llvm/bin", "/usr/local/opt/llvm/bin", "/opt/homebrew/opt/cmake/bin", "/usr/local/opt/cmake/bin"]
        .into_iter()
        .map(PathBuf::from)
        .collect()
}

fn is_executable(path: &std::path::Path) -> bool {
    path.is_file()
}

fn teeworlds_vm_probe(args: &TeeworldsVmProbeArgs) -> Result<TeeworldsVmProbeReport> {
    let replayer = fs::read(&args.replayer)?;
    let tape = fs::read(&args.tape)?;
    let map = fs::read(&args.map)?;
    let config = fs::read(&args.config)?;

    let script_code_hash = blake3_32(b"myelin:teeworlds-replayer-code:v1", &replayer);
    let lock_script = Script::new([0x11; 32], 0, vec![]);
    let type_script = Script::new(script_code_hash, 0, vec![]);
    let input_cell = CellOutput { lock: lock_script.clone(), type_: Some(type_script.clone()), capacity: 1_000 };
    let output_cell = CellOutput { lock: lock_script, type_: Some(type_script), capacity: 990 };
    let input_out_points = (0..4)
        .map(|index| {
            let mut tx_hash = [0x22; 32];
            tx_hash[0] = 0x22 + index as u8;
            OutPoint::new(tx_hash, 0)
        })
        .collect::<Vec<_>>();
    let tx = CellTx::new(
        input_out_points.iter().copied().map(|out_point| CellInput::new(out_point, 0)).collect(),
        vec![],
        vec![output_cell],
        vec![Vec::new()],
        vec![Vec::new(), tape.clone(), map.clone(), config.clone()],
    )
    .map_err(|error| CliError::InvalidFixture(error.to_owned()))?;

    let mut provider = SimpleDataProvider::new();
    provider.add_script(script_code_hash, replayer);
    for input_out_point in &input_out_points {
        provider.add_cell(
            input_out_point.tx_hash,
            input_out_point.index,
            ResolvedCell { cell_output: input_cell.clone(), data: Some(Vec::new()) },
        );
    }

    let verifier = TransactionScriptVerifier::new(Arc::new(tx), Arc::new(provider))
        .with_skip_lock_groups(true)
        .with_semantics(VmSemantics::CkbStrict)
        .with_version(ScriptVersion::latest())
        .with_max_cycles(args.max_cycles);

    let result = verifier.verify_with_cycles();
    let (success, cycles, error) = match result {
        Ok(cycles) => (true, Some(cycles), None),
        Err(error) => (false, None, Some(error.to_string())),
    };

    Ok(TeeworldsVmProbeReport {
        replayer: args.replayer.display().to_string(),
        tape_bytes: tape.len(),
        map_bytes: map.len(),
        config_bytes: config.len(),
        max_cycles: args.max_cycles,
        ckb_strict: true,
        success,
        cycles,
        error,
    })
}

fn teeworlds_court_bundle(
    path: PathBuf,
    chunk_bytes: usize,
    chunk_index: usize,
    consensus: &str,
) -> Result<TeeworldsCourtBundleReport> {
    if chunk_bytes == 0 {
        return Err(CliError::InvalidFixture("chunk-bytes must be non-zero".to_owned()));
    }
    let consensus_kind = match consensus {
        "static-closed-committee" | "static_closed_committee" => ConsensusKind::StaticClosedCommittee,
        "tendermint" => ConsensusKind::Tendermint,
        other => return Err(CliError::InvalidFixture(format!("unknown consensus engine for court-bundle: {other}"))),
    };

    let bytes = fs::read(&path)?;
    let fixture_hash = *blake3::hash(&bytes).as_bytes();
    let mock_tx_json_hash = hex::encode(fixture_hash);
    let value = serde_json::from_slice::<Value>(&bytes)?;
    let witnesses = find_witnesses(&value)
        .ok_or_else(|| CliError::InvalidFixture("could not find a witnesses array in mock transaction JSON".to_owned()))?;
    if witnesses.len() < 4 {
        return Err(CliError::InvalidFixture(format!("expected at least 4 witnesses, got {}", witnesses.len())));
    }

    let tape = &witnesses[1];
    let map = &witnesses[2];
    let config = &witnesses[3];
    let offset = chunk_index.checked_mul(chunk_bytes).ok_or_else(|| CliError::InvalidFixture("chunk offset overflow".to_owned()))?;
    if offset >= tape.len() {
        return Err(CliError::InvalidFixture(format!(
            "chunk index {chunk_index} is out of range for {} tape bytes and {chunk_bytes} byte chunks",
            tape.len()
        )));
    }

    let end = offset.saturating_add(chunk_bytes).min(tape.len());
    let chunk = &tape[offset..end];
    let commitment = chunk_commitment(chunk_index, offset, chunk);
    let map_hash = blake3_32(b"myelin:teeworlds-map:v1", map);
    let config_hash = blake3_32(b"myelin:teeworlds-config:v1", config);
    let tx = teeworlds_chunk_cell_tx(chunk_index, offset, chunk, commitment, map_hash, config_hash, fixture_hash)
        .map_err(|error| CliError::InvalidFixture(error.to_owned()))?;
    let ckb_projection = TeeworldsChunkProjectionReport::from(project_cell_tx_to_ckb(&tx));
    let molecule_transaction = serialize_transaction_molecule(&tx).map_err(|error| CliError::InvalidFixture(error.to_string()))?;
    let molecule_transaction_hash = blake3_32(b"myelin:ckb-molecule-transaction:v1", &molecule_transaction);

    let index_bytes = (chunk_index as u64).to_le_bytes();
    let session_id = blake3_chunks(b"myelin:teeworlds-session-id:v1", &[&fixture_hash]);
    let old_state_root = blake3_chunks(b"myelin:teeworlds-old-state-root:v1", &[&session_id, &index_bytes]);
    let new_state_root =
        blake3_chunks(b"myelin:teeworlds-new-state-root:v1", &[&old_state_root, &commitment, &map_hash, &config_hash]);
    let chunk_payload_hash = blake3_32(b"myelin:teeworlds-chunk-payload:v1", chunk);
    let scheduler_report_hash = blake3_chunks(b"myelin:teeworlds-scheduler-report:v1", &[&session_id, &index_bytes, &commitment]);

    // Build the canonical MyelinBlock from the runtime evidence. This is
    // the data-binding anchor: every field below is derived from the
    // session / chunk / map / config, and the block hash that the
    // finality certificate is bound to is `MyelinBlock::hash()` over
    // these exact fields.
    let canonical_block = MyelinBlock {
        version: 1,
        parent_hash: [0; 32],
        number: 1,
        timestamp_ms: 0,
        consensus_kind,
        state_root_before: old_state_root,
        state_root_after: new_state_root,
        ordered_cell_tx_commitments: vec![commitment],
        data_commitments: vec![commitment],
        scheduler_commitment: scheduler_report_hash,
    };
    let canonical_block_hash = canonical_block.hash();

    let (static_evidence, tendermint_evidence, evidence_notes) = match consensus_kind {
        ConsensusKind::StaticClosedCommittee => {
            // Build a static-closed-committee cert over the same canonical
            // block. The cert's `block_hash` MUST equal `canonical_block_hash`.
            let committee_config = static_fixture_committee_config();
            let committee = StaticClosedCommittee::new(committee_config.clone()).expect("static fixture committee");
            let signer_ids = vec!["validator-0".to_owned(), "validator-1".to_owned()];
            let cert = committee
                .certificate_for_fixture(canonical_block_hash, &["validator-0", "validator-1"])
                .expect("static fixture certificate");
            committee.finalise_block(canonical_block.clone(), cert.clone()).expect("static fixture finality");
            let signatures = cert
                .signatures
                .iter()
                .map(|signature| CommitteeSignatureEvidenceReport {
                    validator_id: signature.validator_id.clone(),
                    signature: hex::encode(signature.signature),
                    signature_hash: hex::encode(blake3_32(b"myelin:static-committee-signature-hash:v1", &signature.signature)),
                })
                .collect::<Vec<_>>();
            let evidence = StaticCommitteeEvidenceReport {
                consensus_kind: ConsensusKind::StaticClosedCommittee.as_str(),
                block_hash: hex::encode(canonical_block_hash),
                quorum_weight: committee_config.quorum_weight,
                signer_ids,
                signatures,
                finalised: true,
            };
            (evidence, None, vec!["This bundle carries static-closed-committee evidence over the canonical MyelinBlock.".to_owned()])
        }
        ConsensusKind::Tendermint => {
            // Build a Tendermint precommit cert over the same canonical
            // block. The cert's `block_hash` and `height` MUST equal
            // `canonical_block_hash` and `canonical_block.number`. The
            // Tendermint signature domain is independent of the static
            // committee's, so the two paths are not interchangeable.
            let tendermint_engine = tendermint_fixture_engine();
            let height = canonical_block.number;
            let round = 0u32;
            let signer_ids = vec!["validator-0".to_owned(), "validator-1".to_owned()];
            let cert = tendermint_engine
                .precommit_certificate_for_fixture(canonical_block_hash, height, round, &["validator-0", "validator-1"])
                .expect("tendermint fixture certificate");
            tendermint_engine
                .finalise_block_with_precommit(canonical_block.clone(), round, cert.clone())
                .expect("tendermint fixture finality");
            let signatures = cert
                .signatures
                .iter()
                .map(|signature| CommitteeSignatureEvidenceReport {
                    validator_id: signature.validator_id.clone(),
                    signature: hex::encode(signature.signature),
                    signature_hash: hex::encode(blake3_32(b"myelin:tendermint-precommit-signature-hash:v1", &signature.signature)),
                })
                .collect::<Vec<_>>();
            let tendermint_evidence = TendermintEvidenceReport {
                consensus_kind: ConsensusKind::Tendermint.as_str(),
                block_hash: hex::encode(canonical_block_hash),
                quorum_power: 2,
                height,
                round,
                signer_ids,
                signatures,
                certificate_step: "precommit",
                finalised: true,
            };
            // Static evidence is still emitted so the bundle surface stays
            // uniform, but it is informational only — the active finality
            // path is the Tendermint precommit.
            let committee_config = static_fixture_committee_config();
            let quorum_weight = committee_config.quorum_weight;
            let static_evidence = StaticCommitteeEvidenceReport {
                consensus_kind: ConsensusKind::StaticClosedCommittee.as_str(),
                block_hash: hex::encode(canonical_block_hash),
                quorum_weight,
                signer_ids: vec![],
                signatures: vec![],
                finalised: false,
            };
            let mut notes = vec!["This bundle carries Tendermint precommit evidence over the canonical MyelinBlock.".to_owned()];
            notes.push("The static-closed-committee evidence slot is informational; the challenge-payload-hash binds to the canonical block hash.".to_owned());
            (static_evidence, Some(tendermint_evidence), notes)
        }
    };
    let block_hash = canonical_block_hash;

    let challenge_payload_hash = blake3_chunks(
        b"myelin:single-chunk-challenge-payload:v1",
        &[&old_state_root, &chunk_payload_hash, &new_state_root, &scheduler_report_hash, &molecule_transaction_hash, &block_hash],
    );
    let court_verifiable = ckb_projection.ckb_projection_possible && ckb_projection.semantic_profile == "ckb-compatible";

    let mut notes = evidence_notes;
    notes.push("This is a single-chunk court input bundle for CKB-style adjudication design.".to_owned());
    notes.push(
        "It proves the disputed chunk has CKB-compatible transaction shape; it is not yet an on-chain CKB court script.".to_owned(),
    );

    let bundle_block = TeeworldsBundleBlock {
        version: canonical_block.version,
        parent_hash: hex::encode(canonical_block.parent_hash),
        number: canonical_block.number,
        timestamp_ms: canonical_block.timestamp_ms,
        consensus_kind: canonical_block.consensus_kind.as_str().to_string(),
        state_root_before: hex::encode(canonical_block.state_root_before),
        state_root_after: hex::encode(canonical_block.state_root_after),
        ordered_cell_tx_commitments: canonical_block.ordered_cell_tx_commitments.iter().map(hex::encode).collect(),
        data_commitments: canonical_block.data_commitments.iter().map(hex::encode).collect(),
        scheduler_commitment: hex::encode(canonical_block.scheduler_commitment),
        block_hash: hex::encode(canonical_block_hash),
    };

    Ok(TeeworldsCourtBundleReport {
        source: path.display().to_string(),
        mock_tx_json_hash,
        chunk_index,
        chunk_offset: offset,
        chunk_bytes: chunk.len(),
        chunk_payload_hex: hex::encode(chunk),
        session_id: hex::encode(session_id),
        old_state_root: hex::encode(old_state_root),
        new_state_root: hex::encode(new_state_root),
        chunk_payload_hash: hex::encode(chunk_payload_hash),
        map_hash: hex::encode(map_hash),
        config_hash: hex::encode(config_hash),
        chunk_commitment: hex::encode(commitment),
        scheduler_report_hash: hex::encode(scheduler_report_hash),
        block: bundle_block,
        molecule_transaction_bytes: molecule_transaction.len(),
        molecule_transaction_hex: hex::encode(&molecule_transaction),
        molecule_transaction_hash: hex::encode(molecule_transaction_hash),
        challenge_payload_hash: hex::encode(challenge_payload_hash),
        ckb_projection,
        static_committee_evidence: static_evidence,
        tendermint_evidence,
        court_verifiable,
        l1_court_implemented: false,
        notes,
    })
}

fn verify_teeworlds_court_bundle(path: PathBuf) -> Result<TeeworldsCourtBundleVerificationReport> {
    let bytes = fs::read(&path)?;
    let bundle = serde_json::from_slice::<TeeworldsCourtBundleInput>(&bytes)?;
    let mut checks = Vec::new();

    let chunk_payload = decode_hex_field(&bundle.chunk_payload_hex, "chunk_payload_hex")?;
    let expected_chunk_payload_hash = hex::encode(blake3_32(b"myelin:teeworlds-chunk-payload:v1", &chunk_payload));
    push_check(
        &mut checks,
        "chunk-payload-hash",
        expected_chunk_payload_hash == bundle.chunk_payload_hash,
        Some(expected_chunk_payload_hash),
        Some(bundle.chunk_payload_hash.clone()),
        "chunk payload hash matches embedded chunk payload",
    );

    let molecule_transaction = decode_hex_field(&bundle.molecule_transaction_hex, "molecule_transaction_hex")?;
    let expected_molecule_transaction_hash = hex::encode(blake3_32(b"myelin:ckb-molecule-transaction:v1", &molecule_transaction));
    push_check(
        &mut checks,
        "molecule-transaction-hash",
        expected_molecule_transaction_hash == bundle.molecule_transaction_hash,
        Some(expected_molecule_transaction_hash),
        Some(bundle.molecule_transaction_hash.clone()),
        "Molecule transaction hash matches embedded transaction bytes",
    );

    if let Some(expected_len) = bundle.ckb_projection.molecule_transaction_bytes {
        push_check(
            &mut checks,
            "molecule-transaction-length",
            expected_len == molecule_transaction.len(),
            Some(expected_len.to_string()),
            Some(molecule_transaction.len().to_string()),
            "projection byte length matches embedded transaction bytes",
        );
    } else {
        push_check(
            &mut checks,
            "molecule-transaction-length",
            false,
            None,
            Some(molecule_transaction.len().to_string()),
            "projection did not record a Molecule transaction length",
        );
    }

    let tx = deserialize_transaction_molecule(&molecule_transaction).map_err(|error| CliError::InvalidFixture(error.to_string()))?;
    let projection = project_cell_tx_to_ckb(&tx);
    let recomputed_projection = TeeworldsChunkProjectionReport::from(projection);
    push_check(
        &mut checks,
        "projection-possible",
        bundle.ckb_projection.ckb_projection_possible == recomputed_projection.ckb_projection_possible,
        Some(recomputed_projection.ckb_projection_possible.to_string()),
        Some(bundle.ckb_projection.ckb_projection_possible.to_string()),
        "projection possibility recomputes from embedded Molecule transaction",
    );
    push_check(
        &mut checks,
        "projection-profile",
        bundle.ckb_projection.semantic_profile == recomputed_projection.semantic_profile,
        Some(recomputed_projection.semantic_profile.clone()),
        Some(bundle.ckb_projection.semantic_profile.clone()),
        "semantic profile recomputes from embedded Molecule transaction",
    );
    push_check(
        &mut checks,
        "projection-source-txid",
        bundle.ckb_projection.source_txid == recomputed_projection.source_txid,
        Some(recomputed_projection.source_txid.clone()),
        Some(bundle.ckb_projection.source_txid.clone()),
        "source txid recomputes from embedded Molecule transaction",
    );
    push_check(
        &mut checks,
        "projection-raw-tx-hash",
        bundle.ckb_projection.ckb_raw_tx_hash == recomputed_projection.ckb_raw_tx_hash,
        recomputed_projection.ckb_raw_tx_hash.clone(),
        bundle.ckb_projection.ckb_raw_tx_hash.clone(),
        "CKB raw transaction hash recomputes from embedded Molecule transaction",
    );
    push_check(
        &mut checks,
        "projection-wtx-hash",
        bundle.ckb_projection.ckb_wtx_hash == recomputed_projection.ckb_wtx_hash,
        recomputed_projection.ckb_wtx_hash.clone(),
        bundle.ckb_projection.ckb_wtx_hash.clone(),
        "CKB witness transaction hash recomputes from embedded Molecule transaction",
    );

    let old_state_root = parse_hex_32(&bundle.old_state_root)
        .ok_or_else(|| CliError::InvalidFixture("old_state_root must be 32-byte hex".to_owned()))?;
    let chunk_payload_hash = parse_hex_32(&bundle.chunk_payload_hash)
        .ok_or_else(|| CliError::InvalidFixture("chunk_payload_hash must be 32-byte hex".to_owned()))?;
    let new_state_root = parse_hex_32(&bundle.new_state_root)
        .ok_or_else(|| CliError::InvalidFixture("new_state_root must be 32-byte hex".to_owned()))?;
    let scheduler_report_hash = parse_hex_32(&bundle.scheduler_report_hash)
        .ok_or_else(|| CliError::InvalidFixture("scheduler_report_hash must be 32-byte hex".to_owned()))?;
    let molecule_transaction_hash = parse_hex_32(&bundle.molecule_transaction_hash)
        .ok_or_else(|| CliError::InvalidFixture("molecule_transaction_hash must be 32-byte hex".to_owned()))?;

    // ─── Data-binding reconstruction ────────────────────────────────────
    // Reconstruct the canonical MyelinBlock from the bundle's data fields
    // and assert that its hash matches the supplied active block hash.
    // This is the structural guarantee that the finality certificate is
    // bound to THIS bundle's runtime evidence, not to a free-floating
    // claimed block hash.
    let reconstructed_block =
        bundle.block.to_myelin_block().map_err(|error| CliError::InvalidFixture(format!("bundle block: {error}")))?;
    let reconstructed_block_hash = reconstructed_block.hash();
    let supplied_block_hash = parse_hex_32(&bundle.block.block_hash)
        .ok_or_else(|| CliError::InvalidFixture("bundle.block.block_hash must be 32-byte hex".to_owned()))?;
    push_check(
        &mut checks,
        "block-hash-recomputes",
        reconstructed_block_hash == supplied_block_hash,
        Some(hex::encode(reconstructed_block_hash)),
        Some(hex::encode(supplied_block_hash)),
        "bundle.block fields rehash to bundle.block.block_hash",
    );

    // The block's runtime fields must match the bundle's runtime evidence.
    push_check(
        &mut checks,
        "block-state-root-before-matches",
        reconstructed_block.state_root_before == old_state_root,
        Some(hex::encode(reconstructed_block.state_root_before)),
        Some(hex::encode(old_state_root)),
        "bundle.block.state_root_before == bundle.old_state_root",
    );
    push_check(
        &mut checks,
        "block-state-root-after-matches",
        reconstructed_block.state_root_after == new_state_root,
        Some(hex::encode(reconstructed_block.state_root_after)),
        Some(hex::encode(new_state_root)),
        "bundle.block.state_root_after == bundle.new_state_root",
    );
    push_check(
        &mut checks,
        "block-scheduler-commitment-matches",
        reconstructed_block.scheduler_commitment == scheduler_report_hash,
        Some(hex::encode(reconstructed_block.scheduler_commitment)),
        Some(hex::encode(scheduler_report_hash)),
        "bundle.block.scheduler_commitment == bundle.scheduler_report_hash",
    );
    // The bundle's `chunk_commitment` field is what was committed to the
    // cell_data_hash chain. The block's `data_commitments[0]` MUST equal
    // that commitment.
    let bundle_chunk_commitment = parse_hex_32(&bundle.chunk_commitment)
        .ok_or_else(|| CliError::InvalidFixture("chunk_commitment must be 32-byte hex".to_owned()))?;
    push_check(
        &mut checks,
        "block-data-commitment-matches",
        reconstructed_block.data_commitments.first().copied() == Some(bundle_chunk_commitment),
        Some(hex::encode(reconstructed_block.data_commitments.first().copied().unwrap_or([0; 32]))),
        Some(hex::encode(bundle_chunk_commitment)),
        "bundle.block.data_commitments[0] == bundle.chunk_commitment",
    );
    // The active block hash is the reconstructed hash. The supplied
    // static-committee / Tendermint `block_hash` fields must equal it.
    let active_block_hash = reconstructed_block_hash;
    let supplied_evidence_block_hash = match &bundle.tendermint_evidence {
        Some(tm) => parse_hex_32(&tm.block_hash)
            .ok_or_else(|| CliError::InvalidFixture("tendermint block_hash must be 32-byte hex".to_owned()))?,
        None => parse_hex_32(&bundle.static_committee_evidence.block_hash)
            .ok_or_else(|| CliError::InvalidFixture("static committee block_hash must be 32-byte hex".to_owned()))?,
    };
    push_check(
        &mut checks,
        "evidence-block-hash-matches-canonical-block",
        supplied_evidence_block_hash == active_block_hash,
        Some(hex::encode(active_block_hash)),
        Some(hex::encode(supplied_evidence_block_hash)),
        "finality evidence block_hash matches the data-bound canonical block hash",
    );
    let expected_challenge_payload_hash = hex::encode(blake3_chunks(
        b"myelin:single-chunk-challenge-payload:v1",
        &[
            &old_state_root,
            &chunk_payload_hash,
            &new_state_root,
            &scheduler_report_hash,
            &molecule_transaction_hash,
            &active_block_hash,
        ],
    ));
    push_check(
        &mut checks,
        "challenge-payload-hash",
        expected_challenge_payload_hash == bundle.challenge_payload_hash,
        Some(expected_challenge_payload_hash),
        Some(bundle.challenge_payload_hash.clone()),
        "challenge payload hash recomputes from bundle fields",
    );

    let signature_hashes_ok = match &bundle.tendermint_evidence {
        Some(tm) => tm.signatures.iter().all(|signature| {
            decode_hex_field(&signature.signature, "signature")
                .map(|bytes| {
                    hex::encode(blake3_32(b"myelin:tendermint-precommit-signature-hash:v1", &bytes)) == signature.signature_hash
                })
                .unwrap_or(false)
        }),
        None => bundle.static_committee_evidence.signatures.iter().all(|signature| {
            decode_hex_field(&signature.signature, "signature")
                .map(|bytes| hex::encode(blake3_32(b"myelin:static-committee-signature-hash:v1", &bytes)) == signature.signature_hash)
                .unwrap_or(false)
        }),
    };
    let signature_count = match &bundle.tendermint_evidence {
        Some(tm) => tm.signatures.len(),
        None => bundle.static_committee_evidence.signatures.len(),
    };
    push_check(
        &mut checks,
        "committee-signature-hashes",
        signature_hashes_ok,
        Some("all signature hashes recompute".to_owned()),
        Some(format!("{} signatures", signature_count)),
        "each signature hash matches its embedded signature bytes",
    );

    let signer_ids = match &bundle.tendermint_evidence {
        Some(tm) => tm.signatures.iter().map(|signature| signature.validator_id.clone()).collect::<Vec<_>>(),
        None => bundle.static_committee_evidence.signatures.iter().map(|signature| signature.validator_id.clone()).collect::<Vec<_>>(),
    };
    let expected_signer_ids = match &bundle.tendermint_evidence {
        Some(tm) => &tm.signer_ids,
        None => &bundle.static_committee_evidence.signer_ids,
    };
    push_check(
        &mut checks,
        "committee-signer-ids",
        signer_ids == *expected_signer_ids,
        Some(format!("{:?}", signer_ids)),
        Some(format!("{:?}", expected_signer_ids)),
        "signer id list matches embedded certificate signatures",
    );

    if let Some(tm) = &bundle.tendermint_evidence {
        // Tendermint precommit certificate verification
        let tendermint_engine = tendermint_fixture_engine();
        let signatures = tm
            .signatures
            .iter()
            .map(|signature| {
                let bytes = parse_hex_64(&signature.signature)
                    .ok_or_else(|| CliError::InvalidFixture("tendermint signature must be 64-byte hex".to_owned()))?;
                Ok(CommitteeSignature { validator_id: signature.validator_id.clone(), signature: bytes })
            })
            .collect::<Result<Vec<_>>>()?;
        let certificate = myelin_consensus::TendermintPrecommitCertificate {
            block_hash: active_block_hash,
            height: tm.height,
            round: tm.round,
            signatures,
        };
        let certificate_ok =
            tendermint_engine.verify_precommit_certificate(active_block_hash, tm.height, tm.round, &certificate).is_ok();
        push_check(
            &mut checks,
            "tendermint-certificate",
            certificate_ok,
            Some(format!("quorum power {} height {} round {}", 2, tm.height, tm.round)),
            Some(format!("quorum power {}, finalised {}", tm.quorum_power, tm.finalised)),
            "Tendermint precommit certificate verifies against the phase-one fixture engine",
        );
        push_check(
            &mut checks,
            "tendermint-quorum-power",
            tm.quorum_power == 2,
            Some("2".to_owned()),
            Some(tm.quorum_power.to_string()),
            "bundle Tendermint quorum power matches the phase-one fixture engine",
        );
    } else {
        // Static-closed-committee certificate verification
        let block_hash = active_block_hash;
        let committee_config = static_fixture_committee_config();
        let committee = StaticClosedCommittee::new(committee_config.clone())?;
        let signatures = bundle
            .static_committee_evidence
            .signatures
            .iter()
            .map(|signature| {
                let bytes = parse_hex_64(&signature.signature)
                    .ok_or_else(|| CliError::InvalidFixture("committee signature must be 64-byte hex".to_owned()))?;
                Ok(CommitteeSignature { validator_id: signature.validator_id.clone(), signature: bytes })
            })
            .collect::<Result<Vec<_>>>()?;
        let certificate = CommitteeCertificate { block_hash, signatures };
        let certificate_ok = committee.verify_certificate(block_hash, &certificate).is_ok();
        push_check(
            &mut checks,
            "committee-certificate",
            certificate_ok,
            Some(format!("quorum weight {}", committee_config.quorum_weight)),
            Some(format!(
                "quorum weight {}, finalised {}",
                bundle.static_committee_evidence.quorum_weight, bundle.static_committee_evidence.finalised
            )),
            "static committee certificate verifies against the phase-one fixture committee",
        );
        push_check(
            &mut checks,
            "committee-quorum-weight",
            bundle.static_committee_evidence.quorum_weight == committee_config.quorum_weight,
            Some(committee_config.quorum_weight.to_string()),
            Some(bundle.static_committee_evidence.quorum_weight.to_string()),
            "bundle quorum weight matches the phase-one fixture committee",
        );
    }
    push_check(
        &mut checks,
        "court-verifiable-profile",
        bundle.ckb_projection.ckb_projection_possible && bundle.ckb_projection.semantic_profile == "ckb-compatible",
        Some("ckb-compatible + projection possible".to_owned()),
        Some(format!("{} + {}", bundle.ckb_projection.semantic_profile, bundle.ckb_projection.ckb_projection_possible)),
        "bundle is projectable into the CKB-compatible profile",
    );

    let valid = checks.iter().all(|check| check.ok);
    Ok(TeeworldsCourtBundleVerificationReport { bundle: path.display().to_string(), valid, checks })
}

fn push_check(
    checks: &mut Vec<CourtBundleCheck>,
    name: &'static str,
    ok: bool,
    expected: Option<String>,
    actual: Option<String>,
    detail: &'static str,
) {
    checks.push(CourtBundleCheck { name, ok, expected, actual, detail: detail.to_owned() });
}

fn decode_hex_field(value: &str, field: &'static str) -> Result<Vec<u8>> {
    let stripped = value.strip_prefix("0x").unwrap_or(value);
    hex::decode(stripped).map_err(|error| CliError::InvalidFixture(format!("{field} is not valid hex: {error}")))
}

fn build_and_bench_teeworlds_fixture(args: TeeworldsBuildFixtureArgs) -> Result<TeeworldsBuildFixtureReport> {
    let manifest_path = args.teeworlds_root.join("rust-tools/Cargo.toml");
    if !manifest_path.exists() {
        return Err(CliError::InvalidFixture(format!("missing Teeworlds rust-tools manifest: {}", manifest_path.display())));
    }

    let command = vec![
        "cargo".to_owned(),
        "run".to_owned(),
        "--manifest-path".to_owned(),
        manifest_path.display().to_string(),
        "-p".to_owned(),
        "teeworlds-cli".to_owned(),
        "--".to_owned(),
        "utils".to_owned(),
        "build-test-tx".to_owned(),
        "--replayer".to_owned(),
        args.replayer.display().to_string(),
        "--tape".to_owned(),
        args.tape.display().to_string(),
        "--map".to_owned(),
        args.map.display().to_string(),
        "--config".to_owned(),
        args.config.display().to_string(),
        "--output".to_owned(),
        args.mock_tx_output.display().to_string(),
    ];

    let output = Command::new("cargo")
        .arg("run")
        .arg("--manifest-path")
        .arg(&manifest_path)
        .arg("-p")
        .arg("teeworlds-cli")
        .arg("--")
        .arg("utils")
        .arg("build-test-tx")
        .arg("--replayer")
        .arg(&args.replayer)
        .arg("--tape")
        .arg(&args.tape)
        .arg("--map")
        .arg(&args.map)
        .arg("--config")
        .arg(&args.config)
        .arg("--output")
        .arg(&args.mock_tx_output)
        .output()?;

    let builder_stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let builder_stderr = String::from_utf8_lossy(&output.stderr).to_string();
    if !output.status.success() {
        return Err(CliError::InvalidFixture(format!(
            "teeworlds-cli utils build-test-tx failed with status {:?}\nstdout:\n{}\nstderr:\n{}",
            output.status.code(),
            builder_stdout,
            builder_stderr
        )));
    }

    let benchmark = bench_teeworlds_mock_tx(args.mock_tx_output.clone(), args.chunk_bytes, args.runs, &args.consensus)?;
    Ok(TeeworldsBuildFixtureReport {
        teeworlds_root: args.teeworlds_root.display().to_string(),
        command,
        builder_stdout,
        builder_stderr,
        mock_tx_output: args.mock_tx_output.display().to_string(),
        benchmark,
    })
}

fn bench_teeworlds_mock_tx(path: PathBuf, chunk_bytes: usize, runs: usize, consensus: &str) -> Result<TeeworldsBenchmarkReport> {
    if runs == 0 {
        return Err(CliError::InvalidFixture("runs must be non-zero".to_owned()));
    }
    let _consensus_kind = parse_teeworlds_consensus(consensus)?;

    let mut measured_runs = Vec::with_capacity(runs);
    let mut last_fixture = None;
    for index in 0..runs {
        let start = Instant::now();
        let fixture = inspect_teeworlds_mock_tx(path.clone(), chunk_bytes, consensus)?;
        let elapsed_ns = start.elapsed().as_nanos();
        measured_runs.push(TeeworldsBenchmarkRun {
            index,
            elapsed_ns,
            tape_bytes: fixture.tape_bytes,
            chunk_count: fixture.chunks.len(),
        });
        last_fixture = Some(fixture);
    }

    let total = measured_runs.iter().map(|run| run.elapsed_ns).sum::<u128>();
    Ok(TeeworldsBenchmarkReport {
        fixture: last_fixture.expect("at least one run"),
        runs: measured_runs,
        average_elapsed_ns: total / runs as u128,
    })
}

fn finalise_teeworlds_fixture_block(chunks: &[TeeworldsChunkReport], consensus_kind: ConsensusKind) -> CommitteeDemoReport {
    let data_commitments = chunks.iter().map(|chunk| parse_hex_32(&chunk.commitment).expect("chunk commitment")).collect::<Vec<_>>();
    match consensus_kind {
        ConsensusKind::StaticClosedCommittee => {
            let evidence = static_committee_evidence_for_commitments(data_commitments);
            CommitteeDemoReport {
                consensus_kind: evidence.consensus_kind,
                block_hash: evidence.block_hash,
                quorum_weight: evidence.quorum_weight,
                signer_ids: evidence.signer_ids,
                certificate_height: 1,
                certificate_round: None,
                certificate_step: "commit",
                finalised: evidence.finalised,
            }
        }
        ConsensusKind::Tendermint => {
            let tendermint_block = MyelinBlock {
                version: 1,
                parent_hash: [0; 32],
                number: 1,
                timestamp_ms: 0,
                consensus_kind: ConsensusKind::Tendermint,
                state_root_before: [0; 32],
                state_root_after: [9; 32],
                ordered_cell_tx_commitments: vec![[7; 32]],
                data_commitments,
                scheduler_commitment: [8; 32],
            };
            let tendermint_engine = tendermint_fixture_engine();
            let block_hash = tendermint_block.hash();
            let height = tendermint_block.number;
            let round = 0u32;
            let signer_ids = vec!["validator-0".to_owned(), "validator-1".to_owned()];
            let cert = tendermint_engine
                .precommit_certificate_for_fixture(block_hash, height, round, &["validator-0", "validator-1"])
                .expect("tendermint fixture certificate");
            tendermint_engine.finalise_block_with_precommit(tendermint_block, round, cert).expect("tendermint fixture finality");
            CommitteeDemoReport {
                consensus_kind: ConsensusKind::Tendermint.as_str(),
                block_hash: hex::encode(block_hash),
                quorum_weight: 2,
                signer_ids,
                certificate_height: height,
                certificate_round: Some(round),
                certificate_step: "precommit",
                finalised: true,
            }
        }
    }
}

fn static_fixture_committee_config() -> StaticCommitteeConfig {
    StaticCommitteeConfig {
        quorum_weight: 2,
        validators: vec![
            CommitteeValidator { id: "validator-0".to_owned(), public_key: [1; 32], weight: 1 },
            CommitteeValidator { id: "validator-1".to_owned(), public_key: [2; 32], weight: 1 },
            CommitteeValidator { id: "validator-2".to_owned(), public_key: [3; 32], weight: 1 },
        ],
    }
}

fn tendermint_fixture_config() -> TendermintConfig {
    TendermintConfig {
        quorum_power: 2,
        validators: vec![
            CommitteeValidator { id: "validator-0".to_owned(), public_key: [1; 32], weight: 1 },
            CommitteeValidator { id: "validator-1".to_owned(), public_key: [2; 32], weight: 1 },
            CommitteeValidator { id: "validator-2".to_owned(), public_key: [3; 32], weight: 1 },
        ],
    }
}

fn tendermint_fixture_engine() -> Tendermint {
    Tendermint::new(tendermint_fixture_config()).expect("tendermint fixture engine")
}

fn static_committee_evidence_for_commitments(data_commitments: Vec<[u8; 32]>) -> StaticCommitteeEvidenceReport {
    let committee_config = static_fixture_committee_config();
    let committee = StaticClosedCommittee::new(committee_config.clone()).expect("static fixture committee");
    let block = demo_block(data_commitments, ConsensusKind::StaticClosedCommittee);
    let block_hash = block.hash();
    let signer_ids = vec!["validator-0".to_owned(), "validator-1".to_owned()];
    let certificate = committee.certificate_for_fixture(block_hash, &["validator-0", "validator-1"]).expect("fixture certificate");
    committee.finalise_block(block, certificate.clone()).expect("fixture finality");
    let signatures = certificate
        .signatures
        .iter()
        .map(|signature| CommitteeSignatureEvidenceReport {
            validator_id: signature.validator_id.clone(),
            signature: hex::encode(signature.signature),
            signature_hash: hex::encode(blake3_32(b"myelin:static-committee-signature-hash:v1", &signature.signature)),
        })
        .collect::<Vec<_>>();
    StaticCommitteeEvidenceReport {
        consensus_kind: ConsensusKind::StaticClosedCommittee.as_str(),
        block_hash: hex::encode(block_hash),
        quorum_weight: committee_config.quorum_weight,
        signer_ids,
        signatures,
        finalised: true,
    }
}

fn demo_block(data_commitments: Vec<[u8; 32]>, consensus_kind: ConsensusKind) -> MyelinBlock {
    MyelinBlock {
        version: 1,
        parent_hash: [0; 32],
        number: 1,
        timestamp_ms: 0,
        consensus_kind,
        state_root_before: [0; 32],
        state_root_after: [9; 32],
        ordered_cell_tx_commitments: vec![[7; 32]],
        data_commitments,
        scheduler_commitment: [8; 32],
    }
}

fn find_witnesses(value: &Value) -> Option<Vec<Vec<u8>>> {
    match value {
        Value::Object(object) => {
            if let Some(witnesses) = object.get("witnesses").and_then(decode_witness_array) {
                return Some(witnesses);
            }
            for child in object.values() {
                if let Some(witnesses) = find_witnesses(child) {
                    return Some(witnesses);
                }
            }
            None
        }
        Value::Array(values) => values.iter().find_map(find_witnesses),
        _ => None,
    }
}

fn decode_witness_array(value: &Value) -> Option<Vec<Vec<u8>>> {
    let values = value.as_array()?;
    values.iter().map(decode_json_bytes).collect::<Option<Vec<_>>>()
}

fn decode_json_bytes(value: &Value) -> Option<Vec<u8>> {
    match value {
        Value::String(value) => decode_hex_bytes(value),
        Value::Object(object) => object
            .get("content")
            .or_else(|| object.get("data"))
            .or_else(|| object.get("jsonbytes"))
            .and_then(Value::as_str)
            .and_then(decode_hex_bytes),
        _ => None,
    }
}

fn decode_hex_bytes(value: &str) -> Option<Vec<u8>> {
    let stripped = value.strip_prefix("0x").unwrap_or(value);
    if stripped.is_empty() {
        return Some(Vec::new());
    }
    hex::decode(stripped).ok()
}

fn chunk_commitment(index: usize, offset: usize, chunk: &[u8]) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new();
    hasher.update(b"myelin:teeworlds-fixture-chunk:v1");
    hasher.update(&(index as u64).to_le_bytes());
    hasher.update(&(offset as u64).to_le_bytes());
    hasher.update(&(chunk.len() as u64).to_le_bytes());
    hasher.update(chunk);
    *hasher.finalize().as_bytes()
}

fn teeworlds_chunk_projection(
    index: usize,
    offset: usize,
    chunk: &[u8],
    commitment: [u8; 32],
    map_hash: [u8; 32],
    config_hash: [u8; 32],
    fixture_hash: [u8; 32],
) -> TeeworldsChunkProjectionReport {
    let tx = teeworlds_chunk_cell_tx(index, offset, chunk, commitment, map_hash, config_hash, fixture_hash)
        .expect("Teeworlds chunk CellTx shape is internally consistent");
    TeeworldsChunkProjectionReport::from(project_cell_tx_to_ckb(&tx))
}

fn teeworlds_chunk_cell_tx(
    index: usize,
    offset: usize,
    chunk: &[u8],
    commitment: [u8; 32],
    map_hash: [u8; 32],
    config_hash: [u8; 32],
    fixture_hash: [u8; 32],
) -> std::result::Result<CellTx, &'static str> {
    let index_bytes = (index as u64).to_le_bytes();
    let input_tx_hash = blake3_chunks(b"myelin:teeworlds-session-input:v1", &[&fixture_hash, &index_bytes]);
    let type_code_hash = blake3_32(b"myelin:teeworlds-session-type:v1", &fixture_hash);
    let lock_script = Script::new([0x51; 32], 1, fixture_hash.to_vec());
    let mut type_args = Vec::with_capacity(40);
    type_args.extend_from_slice(&fixture_hash);
    type_args.extend_from_slice(&index_bytes);
    let type_script = Script::new(type_code_hash, 1, type_args);

    let input = CellInput::new(OutPoint::new(input_tx_hash, 0), 0);
    let output = CellOutput { lock: lock_script, type_: Some(type_script), capacity: 1_000 };
    let output_data = teeworlds_chunk_output_data(index, offset, chunk.len(), commitment, map_hash, config_hash);
    CellTx::new(vec![input], vec![], vec![output], vec![output_data], vec![chunk.to_vec()])
}

fn teeworlds_chunk_output_data(
    index: usize,
    offset: usize,
    byte_len: usize,
    commitment: [u8; 32],
    map_hash: [u8; 32],
    config_hash: [u8; 32],
) -> Vec<u8> {
    let mut out = Vec::with_capacity(24 + 32 * 3);
    out.extend_from_slice(&(index as u64).to_le_bytes());
    out.extend_from_slice(&(offset as u64).to_le_bytes());
    out.extend_from_slice(&(byte_len as u64).to_le_bytes());
    out.extend_from_slice(&commitment);
    out.extend_from_slice(&map_hash);
    out.extend_from_slice(&config_hash);
    out
}

fn blake3_chunks(domain: &[u8], chunks: &[&[u8]]) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new();
    hasher.update(domain);
    for chunk in chunks {
        hasher.update(chunk);
    }
    *hasher.finalize().as_bytes()
}

fn blake3_32(domain: &[u8], data: &[u8]) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new();
    hasher.update(domain);
    hasher.update(data);
    *hasher.finalize().as_bytes()
}

fn parse_hex_32(value: &str) -> Option<[u8; 32]> {
    let bytes = hex::decode(value).ok()?;
    bytes.try_into().ok()
}

fn parse_hex_64(value: &str) -> Option<[u8; 64]> {
    let bytes = hex::decode(value).ok()?;
    bytes.try_into().ok()
}

impl From<CkbProjectionReport> for TeeworldsChunkProjectionReport {
    fn from(report: CkbProjectionReport) -> Self {
        Self {
            semantic_profile: semantic_profile_label(report.semantic_profile).to_string(),
            ckb_projection_possible: report.ckb_projection_possible,
            blockers: serde_json::to_value(report.blockers).expect("projection blockers serialize"),
            warnings: serde_json::to_value(report.warnings).expect("projection warnings serialize"),
            source_txid: hex::encode(report.source_txid),
            ckb_raw_tx_hash: report.ckb_raw_tx_hash.map(hex::encode),
            ckb_wtx_hash: report.ckb_wtx_hash.map(hex::encode),
            molecule_transaction_bytes: report.molecule_transaction_bytes,
            input_count: report.input_count,
            output_count: report.output_count,
            witness_count: report.witness_count,
        }
    }
}

fn semantic_profile_label(profile: SemanticProfile) -> &'static str {
    match profile {
        SemanticProfile::MyelinNative => "myelin-native",
        SemanticProfile::CkbCompatible => "ckb-compatible",
        SemanticProfile::CkbInspiredOnly => "ckb-inspired-only",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decodes_nested_mock_transaction_witnesses() {
        let json = serde_json::json!({
            "mock_info": {},
            "tx": {
                "witnesses": [
                    "0x",
                    "0x010203",
                    "0x04",
                    "0x636667"
                ]
            }
        });
        let witnesses = find_witnesses(&json).unwrap();
        assert_eq!(witnesses[1], vec![1, 2, 3]);
        assert_eq!(witnesses[2], vec![4]);
        assert_eq!(witnesses[3], b"cfg");
    }

    #[test]
    fn teeworlds_chunk_projection_is_ckb_compatible() {
        let chunk = b"tick";
        let commitment = chunk_commitment(0, 0, chunk);
        let projection = teeworlds_chunk_projection(0, 0, chunk, commitment, [0xAA; 32], [0xBB; 32], [0xCC; 32]);
        assert!(projection.ckb_projection_possible);
        assert_eq!(projection.semantic_profile, "ckb-compatible");
        assert_eq!(projection.input_count, 1);
        assert_eq!(projection.output_count, 1);
        assert_eq!(projection.witness_count, 1);
        assert!(projection.ckb_raw_tx_hash.is_some());
        assert!(projection.ckb_wtx_hash.is_some());
    }

    #[test]
    fn teeworlds_court_bundle_is_single_chunk_projectable() {
        let path = std::env::temp_dir().join(format!("myelin-court-bundle-test-{}.json", std::process::id()));
        let json = serde_json::json!({
            "tx": {
                "witnesses": [
                    "0x",
                    "0x7469636b6e657874",
                    "0x6d6170",
                    "0x636667"
                ]
            }
        });
        std::fs::write(&path, serde_json::to_vec(&json).unwrap()).unwrap();

        let report = teeworlds_court_bundle(path.clone(), 4, 0, "static-closed-committee").unwrap();
        let _ = std::fs::remove_file(path);

        assert!(report.court_verifiable);
        assert!(!report.l1_court_implemented);
        assert_eq!(report.chunk_index, 0);
        assert_eq!(report.chunk_bytes, 4);
        assert_eq!(report.ckb_projection.semantic_profile, "ckb-compatible");
        assert!(report.ckb_projection.ckb_projection_possible);
        assert!(report.static_committee_evidence.finalised);
        assert_eq!(report.static_committee_evidence.signatures.len(), 2);
        assert_eq!(report.challenge_payload_hash.len(), 64);

        let bundle_path = std::env::temp_dir().join(format!("myelin-court-bundle-report-test-{}.json", std::process::id()));
        std::fs::write(&bundle_path, serde_json::to_vec(&report).unwrap()).unwrap();
        let verification = verify_teeworlds_court_bundle(bundle_path.clone()).unwrap();
        let _ = std::fs::remove_file(bundle_path);

        assert!(verification.valid);
        assert!(verification.checks.iter().all(|check| check.ok));
        assert!(verification.checks.iter().any(|check| check.name == "committee-certificate"));
        // The data-binding checks must all pass on a fresh, well-formed bundle.
        assert!(verification.checks.iter().any(|check| check.name == "block-hash-recomputes"));
        assert!(verification.checks.iter().any(|check| check.name == "block-state-root-before-matches"));
        assert!(verification.checks.iter().any(|check| check.name == "block-state-root-after-matches"));
        assert!(verification.checks.iter().any(|check| check.name == "block-scheduler-commitment-matches"));
        assert!(verification.checks.iter().any(|check| check.name == "block-data-commitment-matches"));
        assert!(verification.checks.iter().any(|check| check.name == "evidence-block-hash-matches-canonical-block"));

        // Negative check: tampering with state_root_after must make the
        // data-binding check fail.
        let mut tampered_report = report.clone();
        tampered_report.block.state_root_after = "11".repeat(32);
        tampered_report.new_state_root = "11".repeat(32);
        let tampered_path = std::env::temp_dir().join(format!("myelin-court-bundle-tampered-{}.json", std::process::id()));
        std::fs::write(&tampered_path, serde_json::to_vec(&tampered_report).unwrap()).unwrap();
        let tampered_verification = verify_teeworlds_court_bundle(tampered_path.clone()).unwrap();
        let _ = std::fs::remove_file(tampered_path);
        assert!(!tampered_verification.valid, "tampered state_root_after must fail the data-binding check");
        let tampering_failed = tampered_verification.checks.iter().any(|check| !check.ok);
        assert!(tampering_failed, "tampered bundle must report at least one failed check");
    }

    #[test]
    fn teeworlds_court_bundle_tendermint_precommit_path_verifies() {
        let path = std::env::temp_dir().join(format!("myelin-tendermint-court-bundle-test-{}.json", std::process::id()));
        let json = serde_json::json!({
            "tx": {
                "witnesses": [
                    "0x",
                    "0x7469636b6e657874",
                    "0x6d6170",
                    "0x636667"
                ]
            }
        });
        std::fs::write(&path, serde_json::to_vec(&json).unwrap()).unwrap();

        let report = teeworlds_court_bundle(path.clone(), 4, 0, "tendermint").unwrap();
        let _ = std::fs::remove_file(path);

        assert!(report.court_verifiable);
        assert!(!report.l1_court_implemented);
        assert_eq!(report.chunk_index, 0);
        assert_eq!(report.chunk_bytes, 4);
        assert_eq!(report.ckb_projection.semantic_profile, "ckb-compatible");
        assert!(report.ckb_projection.ckb_projection_possible);

        // The static-closed-committee evidence is reported for completeness;
        // the Tendermint evidence is the active finality path.
        let tm = report.tendermint_evidence.as_ref().expect("tendermint evidence must be present");
        assert_eq!(tm.consensus_kind, "tendermint");
        assert_eq!(tm.quorum_power, 2);
        assert_eq!(tm.height, 1);
        assert_eq!(tm.round, 0);
        assert_eq!(tm.certificate_step, "precommit");
        assert!(tm.finalised);
        assert_eq!(tm.signatures.len(), 2);

        // The static-committee and Tendermint block hashes MUST agree: both
        // engines sign the same canonical MyelinBlock (same data fields,
        // same data-binding block hash), but with different signature
        // domains. The two engines cannot drift on what was finalised.
        let static_block_hash = hex::decode(&report.static_committee_evidence.block_hash).unwrap();
        let tendermint_block_hash = hex::decode(&tm.block_hash).unwrap();
        assert_eq!(static_block_hash, tendermint_block_hash, "static and tendermint must sign the same canonical block hash");

        // The Tendermint signatures must be domain-separated from the static
        // committee signatures. The two sets of signatures should differ
        // even though the underlying block hash is the same.
        let static_signatures: Vec<&str> = report.static_committee_evidence.signatures.iter().map(|s| s.signature.as_str()).collect();
        let tendermint_signatures: Vec<&str> = tm.signatures.iter().map(|s| s.signature.as_str()).collect();
        assert_ne!(
            static_signatures, tendermint_signatures,
            "Tendermint precommit signatures must be domain-separated from static-committee signatures"
        );

        let bundle_path = std::env::temp_dir().join(format!("myelin-tendermint-court-bundle-report-test-{}.json", std::process::id()));
        std::fs::write(&bundle_path, serde_json::to_vec(&report).unwrap()).unwrap();
        let verification = verify_teeworlds_court_bundle(bundle_path.clone()).unwrap();
        let _ = std::fs::remove_file(bundle_path);

        assert!(verification.valid);
        assert!(verification.checks.iter().all(|check| check.ok));
        assert!(verification.checks.iter().any(|check| check.name == "tendermint-certificate"));
        assert!(verification.checks.iter().any(|check| check.name == "block-hash-recomputes"));
        assert!(verification.checks.iter().any(|check| check.name == "evidence-block-hash-matches-canonical-block"));
        // The static-committee-certificate check must NOT be present when
        // Tendermint evidence is in the bundle; otherwise the bundle would
        // be claiming both engines.
        assert!(!verification.checks.iter().any(|check| check.name == "committee-certificate"));
    }
}
