// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Myelin developers
//
// Myelin protocol CLI.

use clap::{Args, Parser, Subcommand};
use myelin_consensus::{
    CommitteeCertificate, CommitteeSignature, CommitteeValidator, ConsensusConfig, ConsensusEngine, ConsensusKind, MyelinBlock,
    SelectedConsensus, StaticClosedCommittee, StaticCommitteeConfig,
};
use myelin_exec::{
    build_cell_tx_execution_report, deserialize_transaction_molecule, project_cell_tx_to_ckb, serialize_transaction_molecule,
    CellInput, CellOutput, CellTx, CkbProjectionReport, OutPoint, ResolvedCell, Script, ScriptVersion, SemanticProfile,
    SimpleDataProvider, TransactionScriptVerifier, VmSemantics,
};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::{fs, path::PathBuf, process::Command, sync::Arc, time::Instant};

#[derive(Debug, Parser)]
#[command(name = "myelin")]
#[command(about = "Myelin finite Cell ledger tools")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Debug, Subcommand)]
enum Commands {
    /// CellTx report commands.
    Celltx(CelltxArgs),
    /// Committee finality commands.
    Committee(CommitteeArgs),
    /// Teeworlds fixture commands.
    Teeworlds(TeeworldsArgs),
}

#[derive(Debug, Args)]
struct CelltxArgs {
    #[command(subcommand)]
    command: CelltxCommand,
}

#[derive(Debug, Subcommand)]
enum CelltxCommand {
    /// Emit a deterministic report for a built-in simple CellTx.
    SimpleReport(OutputArgs),
}

#[derive(Debug, Args)]
struct CommitteeArgs {
    #[command(subcommand)]
    command: CommitteeCommand,
}

#[derive(Debug, Subcommand)]
enum CommitteeCommand {
    /// Finalise a deterministic demo block with a configured static committee.
    FinaliseDemo(CommitteeFinaliseDemoArgs),
}

#[derive(Debug, Args)]
struct CommitteeFinaliseDemoArgs {
    /// TOML consensus config.
    #[arg(long)]
    config: PathBuf,
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct TeeworldsArgs {
    #[command(subcommand)]
    command: TeeworldsCommand,
}

#[derive(Debug, Subcommand)]
enum TeeworldsCommand {
    /// Inspect a CKB mock transaction generated by xxuejie's teeworlds-cli.
    Inspect(TeeworldsInspectArgs),
    /// Measure Teeworlds fixture ingestion and chunk commitment generation.
    Bench(TeeworldsBenchArgs),
    /// Run xxuejie's fixture builder, then benchmark the generated mock transaction.
    BuildFixture(TeeworldsBuildFixtureArgs),
    /// Probe the Teeworlds replayer through Myelin's CKB-VM verifier path.
    VmProbe(TeeworldsVmProbeArgs),
    /// Emit a single-chunk court input bundle for a disputed Teeworlds chunk.
    CourtBundle(TeeworldsCourtBundleArgs),
    /// Verify a previously emitted single-chunk court input bundle.
    VerifyCourtBundle(TeeworldsVerifyCourtBundleArgs),
    /// Check local prerequisites for running xxuejie's Teeworlds CKB fixture.
    Doctor(TeeworldsDoctorArgs),
}

#[derive(Debug, Args)]
struct TeeworldsInspectArgs {
    /// CKB mock transaction JSON from `teeworlds-cli utils build-test-tx`.
    #[arg(long)]
    mock_tx: PathBuf,
    /// Tape chunk size in bytes.
    #[arg(long, default_value_t = 262_144)]
    chunk_bytes: usize,
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct TeeworldsBenchArgs {
    /// CKB mock transaction JSON from `teeworlds-cli utils build-test-tx`.
    #[arg(long)]
    mock_tx: PathBuf,
    /// Tape chunk size in bytes.
    #[arg(long, default_value_t = 262_144)]
    chunk_bytes: usize,
    /// Number of measured runs.
    #[arg(long, default_value_t = 3)]
    runs: usize,
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct TeeworldsBuildFixtureArgs {
    /// Root of the cloned xxuejie Teeworlds repository.
    #[arg(long, default_value = "/Users/arthur/RustroverProjects/teeworlds")]
    teeworlds_root: PathBuf,
    /// Replayer binary passed to `teeworlds-cli utils build-test-tx`.
    #[arg(long)]
    replayer: PathBuf,
    /// Input tape passed to `teeworlds-cli utils build-test-tx`.
    #[arg(long)]
    tape: PathBuf,
    /// Stripped map passed to `teeworlds-cli utils build-test-tx`.
    #[arg(long)]
    map: PathBuf,
    /// Game config passed to `teeworlds-cli utils build-test-tx`.
    #[arg(long)]
    config: PathBuf,
    /// Output CKB mock transaction JSON path.
    #[arg(long)]
    mock_tx_output: PathBuf,
    /// Tape chunk size in bytes for the Myelin benchmark.
    #[arg(long, default_value_t = 262_144)]
    chunk_bytes: usize,
    /// Number of measured Myelin benchmark runs.
    #[arg(long, default_value_t = 3)]
    runs: usize,
    /// Optional output JSON path for the combined report.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct TeeworldsVmProbeArgs {
    /// Replayer binary to execute as the type script.
    #[arg(long)]
    replayer: PathBuf,
    /// Input tape witness.
    #[arg(long)]
    tape: PathBuf,
    /// Stripped map witness.
    #[arg(long)]
    map: PathBuf,
    /// Game config witness.
    #[arg(long)]
    config: PathBuf,
    /// Maximum VM cycles.
    #[arg(long, default_value_t = 70_000_000)]
    max_cycles: u64,
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct TeeworldsCourtBundleArgs {
    /// CKB mock transaction JSON from `teeworlds-cli utils build-test-tx`.
    #[arg(long)]
    mock_tx: PathBuf,
    /// Tape chunk size in bytes.
    #[arg(long, default_value_t = 262_144)]
    chunk_bytes: usize,
    /// Zero-based disputed chunk index.
    #[arg(long, default_value_t = 0)]
    chunk_index: usize,
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct TeeworldsVerifyCourtBundleArgs {
    /// JSON bundle emitted by `teeworlds court-bundle`.
    #[arg(long)]
    bundle: PathBuf,
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct TeeworldsDoctorArgs {
    /// Root of the cloned xxuejie Teeworlds repository.
    #[arg(long, default_value = "/Users/arthur/RustroverProjects/teeworlds")]
    teeworlds_root: PathBuf,
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct OutputArgs {
    /// Optional output JSON path.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, thiserror::Error)]
enum CliError {
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("json error: {0}")]
    Json(#[from] serde_json::Error),
    #[error("consensus error: {0}")]
    Consensus(#[from] myelin_consensus::ConsensusError),
    #[error("invalid fixture: {0}")]
    InvalidFixture(String),
}

type Result<T> = std::result::Result<T, CliError>;

fn main() {
    if let Err(error) = run() {
        eprintln!("error: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Commands::Celltx(args) => match args.command {
            CelltxCommand::SimpleReport(args) => write_json(args.out, &simple_celltx_report()?),
        },
        Commands::Committee(args) => match args.command {
            CommitteeCommand::FinaliseDemo(args) => {
                let report = finalise_demo_from_config(args.config)?;
                write_json(args.out, &report)
            }
        },
        Commands::Teeworlds(args) => match args.command {
            TeeworldsCommand::Inspect(args) => {
                let report = inspect_teeworlds_mock_tx(args.mock_tx, args.chunk_bytes)?;
                write_json(args.out, &report)
            }
            TeeworldsCommand::Bench(args) => {
                let report = bench_teeworlds_mock_tx(args.mock_tx, args.chunk_bytes, args.runs)?;
                write_json(args.out, &report)
            }
            TeeworldsCommand::BuildFixture(args) => {
                let out = args.out.clone();
                let report = build_and_bench_teeworlds_fixture(args)?;
                write_json(out, &report)
            }
            TeeworldsCommand::VmProbe(args) => {
                let report = teeworlds_vm_probe(&args)?;
                write_json(args.out, &report)
            }
            TeeworldsCommand::CourtBundle(args) => {
                let report = teeworlds_court_bundle(args.mock_tx, args.chunk_bytes, args.chunk_index)?;
                write_json(args.out, &report)
            }
            TeeworldsCommand::VerifyCourtBundle(args) => {
                let report = verify_teeworlds_court_bundle(args.bundle)?;
                write_json(args.out, &report)
            }
            TeeworldsCommand::Doctor(args) => {
                let report = teeworlds_doctor(&args.teeworlds_root);
                write_json(args.out, &report)
            }
        },
    }
}

fn write_json<T: Serialize>(path: Option<PathBuf>, value: &T) -> Result<()> {
    let json = serde_json::to_string_pretty(value)?;
    if let Some(path) = path {
        fs::write(path, json)?;
    } else {
        println!("{json}");
    }
    Ok(())
}

fn simple_celltx_report() -> Result<serde_json::Value> {
    let tx = CellTx::new(
        vec![CellInput::new(OutPoint::new([1; 32], 0), 0)],
        vec![],
        vec![CellOutput { lock: Script::new([2; 32], 1, vec![0x42]), type_: None, capacity: 100 }],
        vec![b"myelin-simple-output".to_vec()],
        vec![b"myelin-simple-witness".to_vec()],
    )
    .map_err(|error| CliError::InvalidFixture(error.to_owned()))?;
    let report = build_cell_tx_execution_report(&tx, [0; 32]);
    Ok(serde_json::to_value(report)?)
}

#[derive(Clone, Debug, Serialize)]
struct CommitteeDemoReport {
    consensus_kind: &'static str,
    block_hash: String,
    quorum_weight: u64,
    signer_ids: Vec<String>,
    finalised: bool,
}

fn finalise_demo_from_config(path: PathBuf) -> Result<CommitteeDemoReport> {
    let config_text = fs::read_to_string(path)?;
    let config = ConsensusConfig::from_toml_str(&config_text)?;
    let static_config = config
        .static_committee
        .clone()
        .ok_or_else(|| CliError::InvalidFixture("demo finality requires a static committee config".to_owned()))?;
    let selected = SelectedConsensus::from_config(config)?;
    let committee = StaticClosedCommittee::new(static_config.clone())?;
    let block = demo_block(vec![[0xA1; 32]]);
    let block_hash = block.hash();
    let signer_ids = quorum_signers(&static_config)?;
    let signer_refs = signer_ids.iter().map(String::as_str).collect::<Vec<_>>();
    let certificate = committee.certificate_for_fixture(block_hash, &signer_refs)?;
    selected.finalise_block(block, certificate)?;
    Ok(CommitteeDemoReport {
        consensus_kind: ConsensusKind::StaticClosedCommittee.as_str(),
        block_hash: hex::encode(block_hash),
        quorum_weight: static_config.quorum_weight,
        signer_ids,
        finalised: true,
    })
}

fn quorum_signers(config: &StaticCommitteeConfig) -> Result<Vec<String>> {
    let mut signers = Vec::new();
    let mut weight = 0u64;
    for validator in &config.validators {
        signers.push(validator.id.clone());
        weight =
            weight.checked_add(validator.weight).ok_or_else(|| CliError::InvalidFixture("committee weight overflow".to_owned()))?;
        if weight >= config.quorum_weight {
            return Ok(signers);
        }
    }
    Err(CliError::InvalidFixture("static committee config cannot satisfy quorum".to_owned()))
}

#[derive(Clone, Debug, Serialize)]
struct TeeworldsFixtureReport {
    source: String,
    mock_tx_json_hash: String,
    witness_count: usize,
    witness_bytes: Vec<usize>,
    tape_bytes: usize,
    map_bytes: usize,
    config_bytes: usize,
    chunk_bytes: usize,
    ckb_projection_possible: bool,
    chunks: Vec<TeeworldsChunkReport>,
    finality: CommitteeDemoReport,
}

#[derive(Clone, Debug, Serialize)]
struct TeeworldsChunkReport {
    index: usize,
    offset: usize,
    byte_len: usize,
    commitment: String,
    ckb_projection: TeeworldsChunkProjectionReport,
}

#[derive(Clone, Debug, Serialize)]
struct TeeworldsChunkProjectionReport {
    semantic_profile: String,
    ckb_projection_possible: bool,
    blockers: Value,
    warnings: Value,
    source_txid: String,
    ckb_raw_tx_hash: Option<String>,
    ckb_wtx_hash: Option<String>,
    molecule_transaction_bytes: Option<usize>,
    input_count: usize,
    output_count: usize,
    witness_count: usize,
}

#[derive(Debug, Serialize)]
struct TeeworldsBenchmarkReport {
    fixture: TeeworldsFixtureReport,
    runs: Vec<TeeworldsBenchmarkRun>,
    average_elapsed_ns: u128,
}

#[derive(Debug, Serialize)]
struct TeeworldsBenchmarkRun {
    index: usize,
    elapsed_ns: u128,
    tape_bytes: usize,
    chunk_count: usize,
}

#[derive(Debug, Serialize)]
struct TeeworldsBuildFixtureReport {
    teeworlds_root: String,
    command: Vec<String>,
    builder_stdout: String,
    builder_stderr: String,
    mock_tx_output: String,
    benchmark: TeeworldsBenchmarkReport,
}

#[derive(Debug, Serialize)]
struct TeeworldsVmProbeReport {
    replayer: String,
    tape_bytes: usize,
    map_bytes: usize,
    config_bytes: usize,
    max_cycles: u64,
    ckb_strict: bool,
    success: bool,
    cycles: Option<u64>,
    error: Option<String>,
}

#[derive(Debug, Serialize)]
struct TeeworldsCourtBundleReport {
    source: String,
    mock_tx_json_hash: String,
    chunk_index: usize,
    chunk_offset: usize,
    chunk_bytes: usize,
    chunk_payload_hex: String,
    session_id: String,
    old_state_root: String,
    new_state_root: String,
    chunk_payload_hash: String,
    map_hash: String,
    config_hash: String,
    chunk_commitment: String,
    scheduler_report_hash: String,
    molecule_transaction_bytes: usize,
    molecule_transaction_hex: String,
    molecule_transaction_hash: String,
    challenge_payload_hash: String,
    ckb_projection: TeeworldsChunkProjectionReport,
    static_committee_evidence: StaticCommitteeEvidenceReport,
    court_verifiable: bool,
    l1_court_implemented: bool,
    notes: Vec<String>,
}

#[derive(Debug, Serialize)]
struct TeeworldsCourtBundleVerificationReport {
    bundle: String,
    valid: bool,
    checks: Vec<CourtBundleCheck>,
}

#[derive(Debug, Serialize)]
struct CourtBundleCheck {
    name: &'static str,
    ok: bool,
    expected: Option<String>,
    actual: Option<String>,
    detail: String,
}

#[derive(Debug, Deserialize)]
struct TeeworldsCourtBundleInput {
    chunk_payload_hex: String,
    chunk_payload_hash: String,
    molecule_transaction_hex: String,
    molecule_transaction_hash: String,
    challenge_payload_hash: String,
    old_state_root: String,
    new_state_root: String,
    scheduler_report_hash: String,
    ckb_projection: TeeworldsChunkProjectionInput,
    static_committee_evidence: StaticCommitteeEvidenceInput,
}

#[derive(Debug, Deserialize)]
struct TeeworldsChunkProjectionInput {
    semantic_profile: String,
    ckb_projection_possible: bool,
    source_txid: String,
    ckb_raw_tx_hash: Option<String>,
    ckb_wtx_hash: Option<String>,
    molecule_transaction_bytes: Option<usize>,
}

#[derive(Debug, Deserialize)]
struct StaticCommitteeEvidenceInput {
    block_hash: String,
    quorum_weight: u64,
    signer_ids: Vec<String>,
    signatures: Vec<CommitteeSignatureEvidenceInput>,
    finalised: bool,
}

#[derive(Debug, Deserialize)]
struct CommitteeSignatureEvidenceInput {
    validator_id: String,
    signature: String,
    signature_hash: String,
}

#[derive(Clone, Debug, Serialize)]
struct StaticCommitteeEvidenceReport {
    consensus_kind: &'static str,
    block_hash: String,
    quorum_weight: u64,
    signer_ids: Vec<String>,
    signatures: Vec<CommitteeSignatureEvidenceReport>,
    finalised: bool,
}

#[derive(Clone, Debug, Serialize)]
struct CommitteeSignatureEvidenceReport {
    validator_id: String,
    signature: String,
    signature_hash: String,
}

#[derive(Debug, Serialize)]
struct TeeworldsDoctorReport {
    teeworlds_root: String,
    ready_for_rust_fixture_builder: bool,
    ready_for_ckb_replayer_build: bool,
    ready_for_myelin_vm_probe: bool,
    paths: Vec<PathCheck>,
    tools: Vec<ToolCheck>,
    notes: Vec<String>,
    next_commands: Vec<String>,
}

#[derive(Debug, Serialize)]
struct PathCheck {
    name: &'static str,
    path: String,
    exists: bool,
}

#[derive(Debug, Serialize)]
struct ToolCheck {
    name: &'static str,
    found: bool,
    path: Option<String>,
}

fn inspect_teeworlds_mock_tx(path: PathBuf, chunk_bytes: usize) -> Result<TeeworldsFixtureReport> {
    if chunk_bytes == 0 {
        return Err(CliError::InvalidFixture("chunk-bytes must be non-zero".to_owned()));
    }

    let bytes = fs::read(&path)?;
    let fixture_hash = *blake3::hash(&bytes).as_bytes();
    let mock_tx_json_hash = hex::encode(fixture_hash);
    let value = serde_json::from_slice::<Value>(&bytes)?;
    let witnesses = find_witnesses(&value)
        .ok_or_else(|| CliError::InvalidFixture("could not find a witnesses array in mock transaction JSON".to_owned()))?;
    if witnesses.len() < 4 {
        return Err(CliError::InvalidFixture(format!("expected at least 4 witnesses, got {}", witnesses.len())));
    }

    let witness_bytes = witnesses.iter().map(Vec::len).collect::<Vec<_>>();
    let tape = &witnesses[1];
    let map = &witnesses[2];
    let config = &witnesses[3];
    let map_hash = blake3_32(b"myelin:teeworlds-map:v1", map);
    let config_hash = blake3_32(b"myelin:teeworlds-config:v1", config);
    let chunks = tape
        .chunks(chunk_bytes)
        .enumerate()
        .map(|(index, chunk)| {
            let offset = index * chunk_bytes;
            let commitment = chunk_commitment(index, offset, chunk);
            let ckb_projection = teeworlds_chunk_projection(index, offset, chunk, commitment, map_hash, config_hash, fixture_hash);
            TeeworldsChunkReport { index, offset, byte_len: chunk.len(), commitment: hex::encode(commitment), ckb_projection }
        })
        .collect::<Vec<_>>();
    let ckb_projection_possible = chunks.iter().all(|chunk| chunk.ckb_projection.ckb_projection_possible);
    let finality = finalise_teeworlds_fixture_block(&chunks);

    Ok(TeeworldsFixtureReport {
        source: path.display().to_string(),
        mock_tx_json_hash,
        witness_count: witnesses.len(),
        witness_bytes,
        tape_bytes: tape.len(),
        map_bytes: map.len(),
        config_bytes: config.len(),
        chunk_bytes,
        ckb_projection_possible,
        chunks,
        finality,
    })
}

fn teeworlds_doctor(teeworlds_root: &std::path::Path) -> TeeworldsDoctorReport {
    let rust_tools_manifest = teeworlds_root.join("rust-tools/Cargo.toml");
    let ckb_makefile = teeworlds_root.join("ckb/Makefile");
    let ckb_replayer = teeworlds_root.join("ckb/build/replayer_stripped");
    let generated_protocol = teeworlds_root.join("build/src/generated/protocol.cpp");
    let paths = vec![
        path_check("teeworlds-root", teeworlds_root.to_path_buf()),
        path_check("rust-tools-manifest", rust_tools_manifest.clone()),
        path_check("ckb-makefile", ckb_makefile),
        path_check("ckb-c-stdlib", teeworlds_root.join("ckb/ckb-c-stdlib")),
        path_check("ckb-musl", teeworlds_root.join("ckb/musl")),
        path_check("ckb-builtins", teeworlds_root.join("ckb/builtins")),
        path_check("ckb-libcxx", teeworlds_root.join("ckb/libcxx")),
        path_check("generated-protocol", generated_protocol),
        path_check("replayer-stripped", ckb_replayer.clone()),
    ];
    let tools = vec![
        tool_check("cargo"),
        tool_check("clang"),
        tool_check("clang++"),
        tool_check("ld.lld"),
        tool_check("llvm-objcopy"),
        tool_check("llvm-ar"),
        tool_check("cmake"),
        tool_check("make"),
        tool_check("python3"),
    ];

    let path_exists = |name: &str| paths.iter().find(|path| path.name == name).map(|path| path.exists).unwrap_or(false);
    let tool_found = |name: &str| tools.iter().find(|tool| tool.name == name).map(|tool| tool.found).unwrap_or(false);

    let ready_for_rust_fixture_builder = path_exists("teeworlds-root") && path_exists("rust-tools-manifest") && tool_found("cargo");
    let ready_for_ckb_replayer_build = path_exists("teeworlds-root")
        && path_exists("ckb-makefile")
        && path_exists("ckb-c-stdlib")
        && path_exists("ckb-musl")
        && path_exists("ckb-builtins")
        && path_exists("ckb-libcxx")
        && path_exists("generated-protocol")
        && tool_found("clang")
        && tool_found("clang++")
        && tool_found("ld.lld")
        && tool_found("llvm-objcopy")
        && tool_found("llvm-ar")
        && tool_found("make");
    let ready_for_myelin_vm_probe = path_exists("replayer-stripped");

    let mut notes = Vec::new();
    if !path_exists("generated-protocol") {
        notes.push("Run Teeworlds' top-level CMake build first so build/src/generated/protocol.cpp exists.".to_owned());
    }
    if !path_exists("replayer-stripped") {
        notes.push("Build teeworlds/ckb/build/replayer_stripped before probing the real Teeworlds VM path.".to_owned());
    }
    if !tool_found("llvm-objcopy") || !tool_found("llvm-ar") || !tool_found("ld.lld") {
        notes.push("Install LLVM tools and ensure llvm-objcopy, llvm-ar, and ld.lld are on PATH.".to_owned());
    }
    if !ready_for_ckb_replayer_build {
        notes.push("The CKB replayer build is not ready on this machine yet; Myelin can still run fixture-builder and VM-probe commands when supplied with a valid ELF.".to_owned());
    }

    TeeworldsDoctorReport {
        teeworlds_root: teeworlds_root.display().to_string(),
        ready_for_rust_fixture_builder,
        ready_for_ckb_replayer_build,
        ready_for_myelin_vm_probe,
        paths,
        tools,
        notes,
        next_commands: vec![
            "cd /Users/arthur/RustroverProjects/teeworlds && git submodule update --init --recursive".to_owned(),
            "cd /Users/arthur/RustroverProjects/teeworlds && cmake -S . -B build && cmake --build build --target teeworlds_replayer -j4".to_owned(),
            "cd /Users/arthur/RustroverProjects/teeworlds/ckb && PATH=\"/opt/homebrew/opt/llvm/bin:$PATH\" make CLANG=/opt/homebrew/opt/llvm/bin/clang LD=/opt/homebrew/bin/ld.lld".to_owned(),
            "cargo run -p myelin-cli -- teeworlds vm-probe --replayer /Users/arthur/RustroverProjects/teeworlds/ckb/build/replayer_stripped --tape path/to/tape.bin --map path/to/stripped.map --config path/to/test_game.cfg".to_owned(),
        ],
    }
}

fn path_check(name: &'static str, path: PathBuf) -> PathCheck {
    PathCheck { name, exists: path.exists(), path: path.display().to_string() }
}

fn tool_check(name: &'static str) -> ToolCheck {
    let path = find_executable(name);
    ToolCheck { name, found: path.is_some(), path: path.map(|path| path.display().to_string()) }
}

fn find_executable(name: &str) -> Option<PathBuf> {
    let candidate = std::path::Path::new(name);
    if candidate.components().count() > 1 && is_executable(candidate) {
        return Some(candidate.to_path_buf());
    }
    let path_match = std::env::var_os("PATH")
        .and_then(|path_var| std::env::split_paths(&path_var).map(|dir| dir.join(name)).find(|candidate| is_executable(candidate)));
    path_match.or_else(|| fallback_tool_dirs().into_iter().map(|dir| dir.join(name)).find(|candidate| is_executable(candidate)))
}

fn fallback_tool_dirs() -> Vec<PathBuf> {
    ["/opt/homebrew/opt/llvm/bin", "/usr/local/opt/llvm/bin", "/opt/homebrew/opt/cmake/bin", "/usr/local/opt/cmake/bin"]
        .into_iter()
        .map(PathBuf::from)
        .collect()
}

fn is_executable(path: &std::path::Path) -> bool {
    path.is_file()
}

fn teeworlds_vm_probe(args: &TeeworldsVmProbeArgs) -> Result<TeeworldsVmProbeReport> {
    let replayer = fs::read(&args.replayer)?;
    let tape = fs::read(&args.tape)?;
    let map = fs::read(&args.map)?;
    let config = fs::read(&args.config)?;

    let script_code_hash = blake3_32(b"myelin:teeworlds-replayer-code:v1", &replayer);
    let lock_script = Script::new([0x11; 32], 0, vec![]);
    let type_script = Script::new(script_code_hash, 0, vec![]);
    let input_cell = CellOutput { lock: lock_script.clone(), type_: Some(type_script.clone()), capacity: 1_000 };
    let output_cell = CellOutput { lock: lock_script, type_: Some(type_script), capacity: 990 };
    let input_out_points = (0..4)
        .map(|index| {
            let mut tx_hash = [0x22; 32];
            tx_hash[0] = 0x22 + index as u8;
            OutPoint::new(tx_hash, 0)
        })
        .collect::<Vec<_>>();
    let tx = CellTx::new(
        input_out_points.iter().copied().map(|out_point| CellInput::new(out_point, 0)).collect(),
        vec![],
        vec![output_cell],
        vec![Vec::new()],
        vec![Vec::new(), tape.clone(), map.clone(), config.clone()],
    )
    .map_err(|error| CliError::InvalidFixture(error.to_owned()))?;

    let mut provider = SimpleDataProvider::new();
    provider.add_script(script_code_hash, replayer);
    for input_out_point in &input_out_points {
        provider.add_cell(
            input_out_point.tx_hash,
            input_out_point.index,
            ResolvedCell { cell_output: input_cell.clone(), data: Some(Vec::new()) },
        );
    }

    let verifier = TransactionScriptVerifier::new(Arc::new(tx), Arc::new(provider))
        .with_skip_lock_groups(true)
        .with_semantics(VmSemantics::CkbStrict)
        .with_version(ScriptVersion::latest())
        .with_max_cycles(args.max_cycles);

    let result = verifier.verify_with_cycles();
    let (success, cycles, error) = match result {
        Ok(cycles) => (true, Some(cycles), None),
        Err(error) => (false, None, Some(error.to_string())),
    };

    Ok(TeeworldsVmProbeReport {
        replayer: args.replayer.display().to_string(),
        tape_bytes: tape.len(),
        map_bytes: map.len(),
        config_bytes: config.len(),
        max_cycles: args.max_cycles,
        ckb_strict: true,
        success,
        cycles,
        error,
    })
}

fn teeworlds_court_bundle(path: PathBuf, chunk_bytes: usize, chunk_index: usize) -> Result<TeeworldsCourtBundleReport> {
    if chunk_bytes == 0 {
        return Err(CliError::InvalidFixture("chunk-bytes must be non-zero".to_owned()));
    }

    let bytes = fs::read(&path)?;
    let fixture_hash = *blake3::hash(&bytes).as_bytes();
    let mock_tx_json_hash = hex::encode(fixture_hash);
    let value = serde_json::from_slice::<Value>(&bytes)?;
    let witnesses = find_witnesses(&value)
        .ok_or_else(|| CliError::InvalidFixture("could not find a witnesses array in mock transaction JSON".to_owned()))?;
    if witnesses.len() < 4 {
        return Err(CliError::InvalidFixture(format!("expected at least 4 witnesses, got {}", witnesses.len())));
    }

    let tape = &witnesses[1];
    let map = &witnesses[2];
    let config = &witnesses[3];
    let offset = chunk_index.checked_mul(chunk_bytes).ok_or_else(|| CliError::InvalidFixture("chunk offset overflow".to_owned()))?;
    if offset >= tape.len() {
        return Err(CliError::InvalidFixture(format!(
            "chunk index {chunk_index} is out of range for {} tape bytes and {chunk_bytes} byte chunks",
            tape.len()
        )));
    }

    let end = offset.saturating_add(chunk_bytes).min(tape.len());
    let chunk = &tape[offset..end];
    let commitment = chunk_commitment(chunk_index, offset, chunk);
    let map_hash = blake3_32(b"myelin:teeworlds-map:v1", map);
    let config_hash = blake3_32(b"myelin:teeworlds-config:v1", config);
    let tx = teeworlds_chunk_cell_tx(chunk_index, offset, chunk, commitment, map_hash, config_hash, fixture_hash)
        .map_err(|error| CliError::InvalidFixture(error.to_owned()))?;
    let ckb_projection = TeeworldsChunkProjectionReport::from(project_cell_tx_to_ckb(&tx));
    let molecule_transaction = serialize_transaction_molecule(&tx).map_err(|error| CliError::InvalidFixture(error.to_string()))?;
    let molecule_transaction_hash = blake3_32(b"myelin:ckb-molecule-transaction:v1", &molecule_transaction);

    let index_bytes = (chunk_index as u64).to_le_bytes();
    let session_id = blake3_chunks(b"myelin:teeworlds-session-id:v1", &[&fixture_hash]);
    let old_state_root = blake3_chunks(b"myelin:teeworlds-old-state-root:v1", &[&session_id, &index_bytes]);
    let new_state_root =
        blake3_chunks(b"myelin:teeworlds-new-state-root:v1", &[&old_state_root, &commitment, &map_hash, &config_hash]);
    let chunk_payload_hash = blake3_32(b"myelin:teeworlds-chunk-payload:v1", chunk);
    let scheduler_report_hash = blake3_chunks(b"myelin:teeworlds-scheduler-report:v1", &[&session_id, &index_bytes, &commitment]);
    let static_committee_evidence = static_committee_evidence_for_commitments(vec![commitment]);
    let block_hash = parse_hex_32(&static_committee_evidence.block_hash).expect("fixture block hash is hex");
    let challenge_payload_hash = blake3_chunks(
        b"myelin:single-chunk-challenge-payload:v1",
        &[&old_state_root, &chunk_payload_hash, &new_state_root, &scheduler_report_hash, &molecule_transaction_hash, &block_hash],
    );
    let court_verifiable = ckb_projection.ckb_projection_possible && ckb_projection.semantic_profile == "ckb-compatible";

    Ok(TeeworldsCourtBundleReport {
        source: path.display().to_string(),
        mock_tx_json_hash,
        chunk_index,
        chunk_offset: offset,
        chunk_bytes: chunk.len(),
        chunk_payload_hex: hex::encode(chunk),
        session_id: hex::encode(session_id),
        old_state_root: hex::encode(old_state_root),
        new_state_root: hex::encode(new_state_root),
        chunk_payload_hash: hex::encode(chunk_payload_hash),
        map_hash: hex::encode(map_hash),
        config_hash: hex::encode(config_hash),
        chunk_commitment: hex::encode(commitment),
        scheduler_report_hash: hex::encode(scheduler_report_hash),
        molecule_transaction_bytes: molecule_transaction.len(),
        molecule_transaction_hex: hex::encode(&molecule_transaction),
        molecule_transaction_hash: hex::encode(molecule_transaction_hash),
        challenge_payload_hash: hex::encode(challenge_payload_hash),
        ckb_projection,
        static_committee_evidence,
        court_verifiable,
        l1_court_implemented: false,
        notes: vec![
            "This is a single-chunk court input bundle for CKB-style adjudication design.".to_owned(),
            "It proves the disputed chunk has CKB-compatible transaction shape and static-committee evidence; it is not yet an on-chain CKB court script.".to_owned(),
        ],
    })
}

fn verify_teeworlds_court_bundle(path: PathBuf) -> Result<TeeworldsCourtBundleVerificationReport> {
    let bytes = fs::read(&path)?;
    let bundle = serde_json::from_slice::<TeeworldsCourtBundleInput>(&bytes)?;
    let mut checks = Vec::new();

    let chunk_payload = decode_hex_field(&bundle.chunk_payload_hex, "chunk_payload_hex")?;
    let expected_chunk_payload_hash = hex::encode(blake3_32(b"myelin:teeworlds-chunk-payload:v1", &chunk_payload));
    push_check(
        &mut checks,
        "chunk-payload-hash",
        expected_chunk_payload_hash == bundle.chunk_payload_hash,
        Some(expected_chunk_payload_hash),
        Some(bundle.chunk_payload_hash.clone()),
        "chunk payload hash matches embedded chunk payload",
    );

    let molecule_transaction = decode_hex_field(&bundle.molecule_transaction_hex, "molecule_transaction_hex")?;
    let expected_molecule_transaction_hash = hex::encode(blake3_32(b"myelin:ckb-molecule-transaction:v1", &molecule_transaction));
    push_check(
        &mut checks,
        "molecule-transaction-hash",
        expected_molecule_transaction_hash == bundle.molecule_transaction_hash,
        Some(expected_molecule_transaction_hash),
        Some(bundle.molecule_transaction_hash.clone()),
        "Molecule transaction hash matches embedded transaction bytes",
    );

    if let Some(expected_len) = bundle.ckb_projection.molecule_transaction_bytes {
        push_check(
            &mut checks,
            "molecule-transaction-length",
            expected_len == molecule_transaction.len(),
            Some(expected_len.to_string()),
            Some(molecule_transaction.len().to_string()),
            "projection byte length matches embedded transaction bytes",
        );
    } else {
        push_check(
            &mut checks,
            "molecule-transaction-length",
            false,
            None,
            Some(molecule_transaction.len().to_string()),
            "projection did not record a Molecule transaction length",
        );
    }

    let tx = deserialize_transaction_molecule(&molecule_transaction).map_err(|error| CliError::InvalidFixture(error.to_string()))?;
    let projection = project_cell_tx_to_ckb(&tx);
    let recomputed_projection = TeeworldsChunkProjectionReport::from(projection);
    push_check(
        &mut checks,
        "projection-possible",
        bundle.ckb_projection.ckb_projection_possible == recomputed_projection.ckb_projection_possible,
        Some(recomputed_projection.ckb_projection_possible.to_string()),
        Some(bundle.ckb_projection.ckb_projection_possible.to_string()),
        "projection possibility recomputes from embedded Molecule transaction",
    );
    push_check(
        &mut checks,
        "projection-profile",
        bundle.ckb_projection.semantic_profile == recomputed_projection.semantic_profile,
        Some(recomputed_projection.semantic_profile.clone()),
        Some(bundle.ckb_projection.semantic_profile.clone()),
        "semantic profile recomputes from embedded Molecule transaction",
    );
    push_check(
        &mut checks,
        "projection-source-txid",
        bundle.ckb_projection.source_txid == recomputed_projection.source_txid,
        Some(recomputed_projection.source_txid.clone()),
        Some(bundle.ckb_projection.source_txid.clone()),
        "source txid recomputes from embedded Molecule transaction",
    );
    push_check(
        &mut checks,
        "projection-raw-tx-hash",
        bundle.ckb_projection.ckb_raw_tx_hash == recomputed_projection.ckb_raw_tx_hash,
        recomputed_projection.ckb_raw_tx_hash.clone(),
        bundle.ckb_projection.ckb_raw_tx_hash.clone(),
        "CKB raw transaction hash recomputes from embedded Molecule transaction",
    );
    push_check(
        &mut checks,
        "projection-wtx-hash",
        bundle.ckb_projection.ckb_wtx_hash == recomputed_projection.ckb_wtx_hash,
        recomputed_projection.ckb_wtx_hash.clone(),
        bundle.ckb_projection.ckb_wtx_hash.clone(),
        "CKB witness transaction hash recomputes from embedded Molecule transaction",
    );

    let old_state_root = parse_hex_32(&bundle.old_state_root)
        .ok_or_else(|| CliError::InvalidFixture("old_state_root must be 32-byte hex".to_owned()))?;
    let chunk_payload_hash = parse_hex_32(&bundle.chunk_payload_hash)
        .ok_or_else(|| CliError::InvalidFixture("chunk_payload_hash must be 32-byte hex".to_owned()))?;
    let new_state_root = parse_hex_32(&bundle.new_state_root)
        .ok_or_else(|| CliError::InvalidFixture("new_state_root must be 32-byte hex".to_owned()))?;
    let scheduler_report_hash = parse_hex_32(&bundle.scheduler_report_hash)
        .ok_or_else(|| CliError::InvalidFixture("scheduler_report_hash must be 32-byte hex".to_owned()))?;
    let molecule_transaction_hash = parse_hex_32(&bundle.molecule_transaction_hash)
        .ok_or_else(|| CliError::InvalidFixture("molecule_transaction_hash must be 32-byte hex".to_owned()))?;
    let block_hash = parse_hex_32(&bundle.static_committee_evidence.block_hash)
        .ok_or_else(|| CliError::InvalidFixture("static committee block_hash must be 32-byte hex".to_owned()))?;
    let expected_challenge_payload_hash = hex::encode(blake3_chunks(
        b"myelin:single-chunk-challenge-payload:v1",
        &[&old_state_root, &chunk_payload_hash, &new_state_root, &scheduler_report_hash, &molecule_transaction_hash, &block_hash],
    ));
    push_check(
        &mut checks,
        "challenge-payload-hash",
        expected_challenge_payload_hash == bundle.challenge_payload_hash,
        Some(expected_challenge_payload_hash),
        Some(bundle.challenge_payload_hash.clone()),
        "challenge payload hash recomputes from bundle fields",
    );

    let signature_hashes_ok = bundle.static_committee_evidence.signatures.iter().all(|signature| {
        decode_hex_field(&signature.signature, "signature")
            .map(|bytes| hex::encode(blake3_32(b"myelin:static-committee-signature-hash:v1", &bytes)) == signature.signature_hash)
            .unwrap_or(false)
    });
    push_check(
        &mut checks,
        "committee-signature-hashes",
        signature_hashes_ok,
        Some("all signature hashes recompute".to_owned()),
        Some(format!("{} signatures", bundle.static_committee_evidence.signatures.len())),
        "each signature hash matches its embedded signature bytes",
    );

    let signer_ids =
        bundle.static_committee_evidence.signatures.iter().map(|signature| signature.validator_id.clone()).collect::<Vec<_>>();
    push_check(
        &mut checks,
        "committee-signer-ids",
        signer_ids == bundle.static_committee_evidence.signer_ids,
        Some(format!("{:?}", signer_ids)),
        Some(format!("{:?}", bundle.static_committee_evidence.signer_ids)),
        "signer id list matches embedded certificate signatures",
    );

    let committee_config = static_fixture_committee_config();
    let committee = StaticClosedCommittee::new(committee_config.clone())?;
    let signatures = bundle
        .static_committee_evidence
        .signatures
        .iter()
        .map(|signature| {
            let bytes = parse_hex_64(&signature.signature)
                .ok_or_else(|| CliError::InvalidFixture("committee signature must be 64-byte hex".to_owned()))?;
            Ok(CommitteeSignature { validator_id: signature.validator_id.clone(), signature: bytes })
        })
        .collect::<Result<Vec<_>>>()?;
    let certificate = CommitteeCertificate { block_hash, signatures };
    let certificate_ok = committee.verify_certificate(block_hash, &certificate).is_ok();
    push_check(
        &mut checks,
        "committee-certificate",
        certificate_ok,
        Some(format!("quorum weight {}", committee_config.quorum_weight)),
        Some(format!(
            "quorum weight {}, finalised {}",
            bundle.static_committee_evidence.quorum_weight, bundle.static_committee_evidence.finalised
        )),
        "static committee certificate verifies against the phase-one fixture committee",
    );
    push_check(
        &mut checks,
        "committee-quorum-weight",
        bundle.static_committee_evidence.quorum_weight == committee_config.quorum_weight,
        Some(committee_config.quorum_weight.to_string()),
        Some(bundle.static_committee_evidence.quorum_weight.to_string()),
        "bundle quorum weight matches the phase-one fixture committee",
    );
    push_check(
        &mut checks,
        "court-verifiable-profile",
        bundle.ckb_projection.ckb_projection_possible && bundle.ckb_projection.semantic_profile == "ckb-compatible",
        Some("ckb-compatible + projection possible".to_owned()),
        Some(format!("{} + {}", bundle.ckb_projection.semantic_profile, bundle.ckb_projection.ckb_projection_possible)),
        "bundle is projectable into the CKB-compatible profile",
    );

    let valid = checks.iter().all(|check| check.ok);
    Ok(TeeworldsCourtBundleVerificationReport { bundle: path.display().to_string(), valid, checks })
}

fn push_check(
    checks: &mut Vec<CourtBundleCheck>,
    name: &'static str,
    ok: bool,
    expected: Option<String>,
    actual: Option<String>,
    detail: &'static str,
) {
    checks.push(CourtBundleCheck { name, ok, expected, actual, detail: detail.to_owned() });
}

fn decode_hex_field(value: &str, field: &'static str) -> Result<Vec<u8>> {
    let stripped = value.strip_prefix("0x").unwrap_or(value);
    hex::decode(stripped).map_err(|error| CliError::InvalidFixture(format!("{field} is not valid hex: {error}")))
}

fn build_and_bench_teeworlds_fixture(args: TeeworldsBuildFixtureArgs) -> Result<TeeworldsBuildFixtureReport> {
    let manifest_path = args.teeworlds_root.join("rust-tools/Cargo.toml");
    if !manifest_path.exists() {
        return Err(CliError::InvalidFixture(format!("missing Teeworlds rust-tools manifest: {}", manifest_path.display())));
    }

    let command = vec![
        "cargo".to_owned(),
        "run".to_owned(),
        "--manifest-path".to_owned(),
        manifest_path.display().to_string(),
        "-p".to_owned(),
        "teeworlds-cli".to_owned(),
        "--".to_owned(),
        "utils".to_owned(),
        "build-test-tx".to_owned(),
        "--replayer".to_owned(),
        args.replayer.display().to_string(),
        "--tape".to_owned(),
        args.tape.display().to_string(),
        "--map".to_owned(),
        args.map.display().to_string(),
        "--config".to_owned(),
        args.config.display().to_string(),
        "--output".to_owned(),
        args.mock_tx_output.display().to_string(),
    ];

    let output = Command::new("cargo")
        .arg("run")
        .arg("--manifest-path")
        .arg(&manifest_path)
        .arg("-p")
        .arg("teeworlds-cli")
        .arg("--")
        .arg("utils")
        .arg("build-test-tx")
        .arg("--replayer")
        .arg(&args.replayer)
        .arg("--tape")
        .arg(&args.tape)
        .arg("--map")
        .arg(&args.map)
        .arg("--config")
        .arg(&args.config)
        .arg("--output")
        .arg(&args.mock_tx_output)
        .output()?;

    let builder_stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let builder_stderr = String::from_utf8_lossy(&output.stderr).to_string();
    if !output.status.success() {
        return Err(CliError::InvalidFixture(format!(
            "teeworlds-cli utils build-test-tx failed with status {:?}\nstdout:\n{}\nstderr:\n{}",
            output.status.code(),
            builder_stdout,
            builder_stderr
        )));
    }

    let benchmark = bench_teeworlds_mock_tx(args.mock_tx_output.clone(), args.chunk_bytes, args.runs)?;
    Ok(TeeworldsBuildFixtureReport {
        teeworlds_root: args.teeworlds_root.display().to_string(),
        command,
        builder_stdout,
        builder_stderr,
        mock_tx_output: args.mock_tx_output.display().to_string(),
        benchmark,
    })
}

fn bench_teeworlds_mock_tx(path: PathBuf, chunk_bytes: usize, runs: usize) -> Result<TeeworldsBenchmarkReport> {
    if runs == 0 {
        return Err(CliError::InvalidFixture("runs must be non-zero".to_owned()));
    }

    let mut measured_runs = Vec::with_capacity(runs);
    let mut last_fixture = None;
    for index in 0..runs {
        let start = Instant::now();
        let fixture = inspect_teeworlds_mock_tx(path.clone(), chunk_bytes)?;
        let elapsed_ns = start.elapsed().as_nanos();
        measured_runs.push(TeeworldsBenchmarkRun {
            index,
            elapsed_ns,
            tape_bytes: fixture.tape_bytes,
            chunk_count: fixture.chunks.len(),
        });
        last_fixture = Some(fixture);
    }

    let total = measured_runs.iter().map(|run| run.elapsed_ns).sum::<u128>();
    Ok(TeeworldsBenchmarkReport {
        fixture: last_fixture.expect("at least one run"),
        runs: measured_runs,
        average_elapsed_ns: total / runs as u128,
    })
}

fn finalise_teeworlds_fixture_block(chunks: &[TeeworldsChunkReport]) -> CommitteeDemoReport {
    let data_commitments = chunks.iter().map(|chunk| parse_hex_32(&chunk.commitment).expect("chunk commitment")).collect::<Vec<_>>();
    let evidence = static_committee_evidence_for_commitments(data_commitments);
    CommitteeDemoReport {
        consensus_kind: evidence.consensus_kind,
        block_hash: evidence.block_hash,
        quorum_weight: evidence.quorum_weight,
        signer_ids: evidence.signer_ids,
        finalised: evidence.finalised,
    }
}

fn static_fixture_committee_config() -> StaticCommitteeConfig {
    StaticCommitteeConfig {
        quorum_weight: 2,
        validators: vec![
            CommitteeValidator { id: "validator-0".to_owned(), public_key: [1; 32], weight: 1 },
            CommitteeValidator { id: "validator-1".to_owned(), public_key: [2; 32], weight: 1 },
            CommitteeValidator { id: "validator-2".to_owned(), public_key: [3; 32], weight: 1 },
        ],
    }
}

fn static_committee_evidence_for_commitments(data_commitments: Vec<[u8; 32]>) -> StaticCommitteeEvidenceReport {
    let committee_config = static_fixture_committee_config();
    let committee = StaticClosedCommittee::new(committee_config.clone()).expect("static fixture committee");
    let block = demo_block(data_commitments);
    let block_hash = block.hash();
    let signer_ids = vec!["validator-0".to_owned(), "validator-1".to_owned()];
    let certificate = committee.certificate_for_fixture(block_hash, &["validator-0", "validator-1"]).expect("fixture certificate");
    committee.finalise_block(block, certificate.clone()).expect("fixture finality");
    let signatures = certificate
        .signatures
        .iter()
        .map(|signature| CommitteeSignatureEvidenceReport {
            validator_id: signature.validator_id.clone(),
            signature: hex::encode(signature.signature),
            signature_hash: hex::encode(blake3_32(b"myelin:static-committee-signature-hash:v1", &signature.signature)),
        })
        .collect::<Vec<_>>();
    StaticCommitteeEvidenceReport {
        consensus_kind: ConsensusKind::StaticClosedCommittee.as_str(),
        block_hash: hex::encode(block_hash),
        quorum_weight: committee_config.quorum_weight,
        signer_ids,
        signatures,
        finalised: true,
    }
}

fn demo_block(data_commitments: Vec<[u8; 32]>) -> MyelinBlock {
    MyelinBlock {
        version: 1,
        parent_hash: [0; 32],
        number: 1,
        timestamp_ms: 0,
        consensus_kind: ConsensusKind::StaticClosedCommittee,
        state_root_before: [0; 32],
        state_root_after: [9; 32],
        ordered_cell_tx_commitments: vec![[7; 32]],
        data_commitments,
        scheduler_commitment: [8; 32],
    }
}

fn find_witnesses(value: &Value) -> Option<Vec<Vec<u8>>> {
    match value {
        Value::Object(object) => {
            if let Some(witnesses) = object.get("witnesses").and_then(decode_witness_array) {
                return Some(witnesses);
            }
            for child in object.values() {
                if let Some(witnesses) = find_witnesses(child) {
                    return Some(witnesses);
                }
            }
            None
        }
        Value::Array(values) => values.iter().find_map(find_witnesses),
        _ => None,
    }
}

fn decode_witness_array(value: &Value) -> Option<Vec<Vec<u8>>> {
    let values = value.as_array()?;
    values.iter().map(decode_json_bytes).collect::<Option<Vec<_>>>()
}

fn decode_json_bytes(value: &Value) -> Option<Vec<u8>> {
    match value {
        Value::String(value) => decode_hex_bytes(value),
        Value::Object(object) => object
            .get("content")
            .or_else(|| object.get("data"))
            .or_else(|| object.get("jsonbytes"))
            .and_then(Value::as_str)
            .and_then(decode_hex_bytes),
        _ => None,
    }
}

fn decode_hex_bytes(value: &str) -> Option<Vec<u8>> {
    let stripped = value.strip_prefix("0x").unwrap_or(value);
    if stripped.is_empty() {
        return Some(Vec::new());
    }
    hex::decode(stripped).ok()
}

fn chunk_commitment(index: usize, offset: usize, chunk: &[u8]) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new();
    hasher.update(b"myelin:teeworlds-fixture-chunk:v1");
    hasher.update(&(index as u64).to_le_bytes());
    hasher.update(&(offset as u64).to_le_bytes());
    hasher.update(&(chunk.len() as u64).to_le_bytes());
    hasher.update(chunk);
    *hasher.finalize().as_bytes()
}

fn teeworlds_chunk_projection(
    index: usize,
    offset: usize,
    chunk: &[u8],
    commitment: [u8; 32],
    map_hash: [u8; 32],
    config_hash: [u8; 32],
    fixture_hash: [u8; 32],
) -> TeeworldsChunkProjectionReport {
    let tx = teeworlds_chunk_cell_tx(index, offset, chunk, commitment, map_hash, config_hash, fixture_hash)
        .expect("Teeworlds chunk CellTx shape is internally consistent");
    TeeworldsChunkProjectionReport::from(project_cell_tx_to_ckb(&tx))
}

fn teeworlds_chunk_cell_tx(
    index: usize,
    offset: usize,
    chunk: &[u8],
    commitment: [u8; 32],
    map_hash: [u8; 32],
    config_hash: [u8; 32],
    fixture_hash: [u8; 32],
) -> std::result::Result<CellTx, &'static str> {
    let index_bytes = (index as u64).to_le_bytes();
    let input_tx_hash = blake3_chunks(b"myelin:teeworlds-session-input:v1", &[&fixture_hash, &index_bytes]);
    let type_code_hash = blake3_32(b"myelin:teeworlds-session-type:v1", &fixture_hash);
    let lock_script = Script::new([0x51; 32], 1, fixture_hash.to_vec());
    let mut type_args = Vec::with_capacity(40);
    type_args.extend_from_slice(&fixture_hash);
    type_args.extend_from_slice(&index_bytes);
    let type_script = Script::new(type_code_hash, 1, type_args);

    let input = CellInput::new(OutPoint::new(input_tx_hash, 0), 0);
    let output = CellOutput { lock: lock_script, type_: Some(type_script), capacity: 1_000 };
    let output_data = teeworlds_chunk_output_data(index, offset, chunk.len(), commitment, map_hash, config_hash);
    CellTx::new(vec![input], vec![], vec![output], vec![output_data], vec![chunk.to_vec()])
}

fn teeworlds_chunk_output_data(
    index: usize,
    offset: usize,
    byte_len: usize,
    commitment: [u8; 32],
    map_hash: [u8; 32],
    config_hash: [u8; 32],
) -> Vec<u8> {
    let mut out = Vec::with_capacity(24 + 32 * 3);
    out.extend_from_slice(&(index as u64).to_le_bytes());
    out.extend_from_slice(&(offset as u64).to_le_bytes());
    out.extend_from_slice(&(byte_len as u64).to_le_bytes());
    out.extend_from_slice(&commitment);
    out.extend_from_slice(&map_hash);
    out.extend_from_slice(&config_hash);
    out
}

fn blake3_chunks(domain: &[u8], chunks: &[&[u8]]) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new();
    hasher.update(domain);
    for chunk in chunks {
        hasher.update(chunk);
    }
    *hasher.finalize().as_bytes()
}

fn blake3_32(domain: &[u8], data: &[u8]) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new();
    hasher.update(domain);
    hasher.update(data);
    *hasher.finalize().as_bytes()
}

fn parse_hex_32(value: &str) -> Option<[u8; 32]> {
    let bytes = hex::decode(value).ok()?;
    bytes.try_into().ok()
}

fn parse_hex_64(value: &str) -> Option<[u8; 64]> {
    let bytes = hex::decode(value).ok()?;
    bytes.try_into().ok()
}

impl From<CkbProjectionReport> for TeeworldsChunkProjectionReport {
    fn from(report: CkbProjectionReport) -> Self {
        Self {
            semantic_profile: semantic_profile_label(report.semantic_profile).to_string(),
            ckb_projection_possible: report.ckb_projection_possible,
            blockers: serde_json::to_value(report.blockers).expect("projection blockers serialize"),
            warnings: serde_json::to_value(report.warnings).expect("projection warnings serialize"),
            source_txid: hex::encode(report.source_txid),
            ckb_raw_tx_hash: report.ckb_raw_tx_hash.map(hex::encode),
            ckb_wtx_hash: report.ckb_wtx_hash.map(hex::encode),
            molecule_transaction_bytes: report.molecule_transaction_bytes,
            input_count: report.input_count,
            output_count: report.output_count,
            witness_count: report.witness_count,
        }
    }
}

fn semantic_profile_label(profile: SemanticProfile) -> &'static str {
    match profile {
        SemanticProfile::MyelinNative => "myelin-native",
        SemanticProfile::CkbCompatible => "ckb-compatible",
        SemanticProfile::CkbInspiredOnly => "ckb-inspired-only",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decodes_nested_mock_transaction_witnesses() {
        let json = serde_json::json!({
            "mock_info": {},
            "tx": {
                "witnesses": [
                    "0x",
                    "0x010203",
                    "0x04",
                    "0x636667"
                ]
            }
        });
        let witnesses = find_witnesses(&json).unwrap();
        assert_eq!(witnesses[1], vec![1, 2, 3]);
        assert_eq!(witnesses[2], vec![4]);
        assert_eq!(witnesses[3], b"cfg");
    }

    #[test]
    fn teeworlds_chunk_projection_is_ckb_compatible() {
        let chunk = b"tick";
        let commitment = chunk_commitment(0, 0, chunk);
        let projection = teeworlds_chunk_projection(0, 0, chunk, commitment, [0xAA; 32], [0xBB; 32], [0xCC; 32]);
        assert!(projection.ckb_projection_possible);
        assert_eq!(projection.semantic_profile, "ckb-compatible");
        assert_eq!(projection.input_count, 1);
        assert_eq!(projection.output_count, 1);
        assert_eq!(projection.witness_count, 1);
        assert!(projection.ckb_raw_tx_hash.is_some());
        assert!(projection.ckb_wtx_hash.is_some());
    }

    #[test]
    fn teeworlds_court_bundle_is_single_chunk_projectable() {
        let path = std::env::temp_dir().join(format!("myelin-court-bundle-test-{}.json", std::process::id()));
        let json = serde_json::json!({
            "tx": {
                "witnesses": [
                    "0x",
                    "0x7469636b6e657874",
                    "0x6d6170",
                    "0x636667"
                ]
            }
        });
        std::fs::write(&path, serde_json::to_vec(&json).unwrap()).unwrap();

        let report = teeworlds_court_bundle(path.clone(), 4, 0).unwrap();
        let _ = std::fs::remove_file(path);

        assert!(report.court_verifiable);
        assert!(!report.l1_court_implemented);
        assert_eq!(report.chunk_index, 0);
        assert_eq!(report.chunk_bytes, 4);
        assert_eq!(report.ckb_projection.semantic_profile, "ckb-compatible");
        assert!(report.ckb_projection.ckb_projection_possible);
        assert!(report.static_committee_evidence.finalised);
        assert_eq!(report.static_committee_evidence.signatures.len(), 2);
        assert_eq!(report.challenge_payload_hash.len(), 64);

        let bundle_path = std::env::temp_dir().join(format!("myelin-court-bundle-report-test-{}.json", std::process::id()));
        std::fs::write(&bundle_path, serde_json::to_vec(&report).unwrap()).unwrap();
        let verification = verify_teeworlds_court_bundle(bundle_path.clone()).unwrap();
        let _ = std::fs::remove_file(bundle_path);

        assert!(verification.valid);
        assert!(verification.checks.iter().all(|check| check.ok));
        assert!(verification.checks.iter().any(|check| check.name == "committee-certificate"));
    }
}
